SET NAMES utf8mb4;

CREATE TABLE `mg_bets_template` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `bet_no` varchar(40) NOT NULL COMMENT 'MG 注单号，包含 UTC 创建日期',
  `merchant_id` bigint unsigned NOT NULL COMMENT '商户 ID',
  `user_id` bigint unsigned NOT NULL COMMENT '玩家 ID',
  `platform_code` varchar(32) NOT NULL COMMENT '游戏平台编码',
  `brand_id` bigint unsigned NOT NULL COMMENT '品牌资源 ID',
  `game_id` bigint unsigned NOT NULL COMMENT '游戏资源 ID',
  `currency_code` varchar(16) NOT NULL COMMENT '业务钱包编码',
  `round_key` char(64) NOT NULL COMMENT '上游对局幂等作用域 SHA-256',
  `provider_parent_round_id` varchar(128) DEFAULT NULL COMMENT '上游父局号',
  `provider_round_id` varchar(128) NOT NULL COMMENT '上游局号',
  `bet_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '累计下注额',
  `valid_bet_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '累计有效下注额',
  `win_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '累计派奖额',
  `bet_rollback_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '累计下注回滚额',
  `win_rollback_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '累计派奖回滚额',
  `ggr_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '原始 GGR，可为负数',
  `debit_count` int unsigned NOT NULL DEFAULT '0' COMMENT '下注动作数量',
  `credit_count` int unsigned NOT NULL DEFAULT '0' COMMENT '派奖动作数量',
  `rollback_count` int unsigned NOT NULL DEFAULT '0' COMMENT '回滚动作数量',
  `actions` json DEFAULT NULL COMMENT '对局资金动作摘要',
  `billing_mode` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '交易发生时商户计费方案快照',
  `settlement_enabled` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '交易钱包是否参与费用结算',
  `billable_ggr_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '参与计费的正 GGR',
  `merchant_rate_value` decimal(16,10) NOT NULL DEFAULT '0.0000000000' COMMENT '商户 GGR 费率快照',
  `merchant_fee` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '已确认商户服务费',
  `upstream_rate_value` decimal(16,10) NOT NULL DEFAULT '0.0000000000' COMMENT '上游成本费率快照',
  `upstream_fee` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '已确认上游成本',
  `reserved_fee` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '下注中预留服务费',
  `status` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '状态：0待下注，1进行中，2已结单，3已取消，4异常',
  `business_date` date NOT NULL COMMENT '按商户业务时区计算的营业日期',
  `platform_date` date NOT NULL COMMENT '按 mg_configs.platform_timezone 计算的平台统计日期',
  `settled_time` datetime(3) DEFAULT NULL COMMENT 'UTC 最终结单时间',
  `create_time` datetime(3) NOT NULL,
  `update_time` datetime(3) NOT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bet_no` (`bet_no`),
  UNIQUE KEY `uk_platform_round` (`platform_code`,`round_key`),
  KEY `idx_merchant_date` (`merchant_id`,`business_date`,`id`),
  KEY `idx_platform_date` (`platform_date`,`merchant_id`,`id`),
  KEY `idx_user_time` (`user_id`,`create_time`,`id`),
  KEY `idx_status_time` (`status`,`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='注单月表模板';

CREATE TABLE `mg_bills_template` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `bill_no` varchar(40) NOT NULL COMMENT 'MG 玩家流水号，包含 UTC 创建日期',
  `bet_no` varchar(40) DEFAULT NULL COMMENT '关联 MG 注单号',
  `merchant_id` bigint unsigned NOT NULL COMMENT '商户 ID',
  `user_id` bigint unsigned NOT NULL COMMENT '玩家 ID',
  `game_id` bigint unsigned NOT NULL COMMENT '游戏资源 ID',
  `type` tinyint unsigned NOT NULL COMMENT '流水类型：1下注，2派奖，3下注回滚，4派奖回滚',
  `source` varchar(32) NOT NULL COMMENT '游戏平台编码',
  `source_no` varchar(128) NOT NULL COMMENT '上游交易标识',
  `amount` decimal(24,8) NOT NULL COMMENT '流水金额',
  `currency_code` varchar(16) NOT NULL COMMENT '业务钱包编码',
  `original_bill_no` varchar(40) DEFAULT NULL COMMENT '回滚对应的原 MG 流水号',
  `idempotency_key` char(64) NOT NULL COMMENT '上游资金动作幂等作用域 SHA-256',
  `request_hash` char(64) NOT NULL COMMENT '规范化请求内容 SHA-256',
  `status` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '状态：0待处理，1处理中，2成功，3失败，4结果未知',
  `data` json DEFAULT NULL COMMENT '请求和商户响应摘要',
  `business_date` date NOT NULL COMMENT '按商户业务时区计算的营业日期',
  `platform_date` date NOT NULL COMMENT '按 mg_configs.platform_timezone 计算的平台统计日期',
  `received_time` datetime(3) NOT NULL COMMENT 'UTC 接收请求时间',
  `completed_time` datetime(3) DEFAULT NULL COMMENT 'UTC 完成时间',
  `create_time` datetime(3) NOT NULL,
  `update_time` datetime(3) NOT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bill_no` (`bill_no`),
  UNIQUE KEY `uk_source_idempotency` (`source`,`idempotency_key`),
  KEY `idx_bet` (`bet_no`,`id`),
  KEY `idx_merchant_date` (`merchant_id`,`business_date`,`id`),
  KEY `idx_platform_date` (`platform_date`,`merchant_id`,`id`),
  KEY `idx_user_time` (`user_id`,`create_time`,`id`),
  KEY `idx_status_time` (`status`,`update_time`),
  KEY `idx_original` (`original_bill_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='玩家资金流水月表模板';

CREATE TABLE `mg_configs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `type` varchar(32) NOT NULL COMMENT '后台配置分组',
  `code` varchar(64) NOT NULL COMMENT '全局唯一配置编码',
  `name` varchar(100) NOT NULL COMMENT '后台显示名称',
  `value` json NOT NULL COMMENT '配置值 JSON',
  `remark` varchar(500) DEFAULT NULL COMMENT '运营说明',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '状态：0停用，1启用',
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code` (`code`),
  KEY `idx_type_status` (`type`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='全局业务配置';

CREATE TABLE `mg_daily_stats` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_date` date NOT NULL COMMENT '商户业务日期；商户报表按此字段汇总',
  `platform_date` date NOT NULL COMMENT '平台统计日期；平台报表按此字段汇总',
  `merchant_id` bigint unsigned NOT NULL COMMENT '商户 ID',
  `platform_code` varchar(32) NOT NULL COMMENT '游戏平台编码',
  `brand_id` bigint unsigned NOT NULL COMMENT '品牌资源 ID',
  `game_id` bigint unsigned NOT NULL COMMENT '游戏资源 ID',
  `currency_code` varchar(16) NOT NULL COMMENT '原始业务钱包编码',
  `user_count` bigint unsigned NOT NULL DEFAULT '0' COMMENT '当前维度去重玩家数',
  `bet_count` bigint unsigned NOT NULL DEFAULT '0' COMMENT '注单数量',
  `bill_count` bigint unsigned NOT NULL DEFAULT '0' COMMENT '玩家资金流水数量',
  `bet_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '原始下注总额',
  `valid_bet_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '原始有效下注总额',
  `win_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '原始派奖总额',
  `rollback_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '原始回滚总额',
  `ggr_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '原始 GGR，可为负数',
  `billable_ggr_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '参与计费的正 GGR',
  `upstream_fee` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '上游成本费用',
  `merchant_fee` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '向商户收取的服务费',
  `platform_currency_code` varchar(16) DEFAULT NULL COMMENT '生成时采用的平台统计币种快照',
  `exchange_rate_id` bigint unsigned DEFAULT NULL COMMENT '实际采用的汇率快照 ID',
  `exchange_rate_value` decimal(36,18) DEFAULT NULL COMMENT '1 单位原始金额换算的平台币种数量',
  `platform_bet_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '折算后的平台下注总额',
  `platform_valid_bet_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '折算后的平台有效下注总额',
  `platform_win_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '折算后的平台派奖总额',
  `platform_ggr_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '折算后的平台 GGR',
  `platform_upstream_fee` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '折算后的平台上游成本',
  `platform_merchant_fee` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '折算后的平台商户收入',
  `exception_count` bigint unsigned NOT NULL DEFAULT '0' COMMENT '异常注单数量',
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_daily` (`business_date`,`platform_date`,`merchant_id`,`platform_code`,`brand_id`,`game_id`,`currency_code`),
  KEY `idx_merchant_business_date` (`merchant_id`,`business_date`),
  KEY `idx_platform_date` (`platform_date`,`merchant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='游戏每日统计';

CREATE TABLE `mg_enterprise_user_merchants` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `enterprise_user_id` bigint unsigned NOT NULL COMMENT '企业后台账号范围 ID',
  `merchant_id` bigint unsigned NOT NULL COMMENT '允许访问的商户 ID',
  `created_by` bigint unsigned DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_merchant` (`enterprise_user_id`,`merchant_id`),
  KEY `idx_merchant` (`merchant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='企业子账号商户范围';

CREATE TABLE `mg_enterprise_users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `enterprise_id` bigint unsigned NOT NULL COMMENT '企业 ID',
  `system_user_id` bigint unsigned NOT NULL COMMENT 'SaiAdmin 系统用户 ID',
  `is_owner` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否企业负责人',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '状态：0停用，1启用',
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_system_user` (`system_user_id`),
  KEY `idx_enterprise_status` (`enterprise_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='企业后台账号范围';

CREATE TABLE `mg_enterprises` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL COMMENT '企业名称',
  `merchant_limit` int unsigned NOT NULL DEFAULT '1' COMMENT '允许创建的商户参数数量',
  `timezone` varchar(64) NOT NULL DEFAULT 'UTC' COMMENT '企业默认 IANA 时区；仅作为新建商户的默认值',
  `default_language` varchar(16) NOT NULL DEFAULT 'en' COMMENT '企业默认语言编码',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '状态：0停用，1启用',
  `remark` varchar(500) DEFAULT NULL COMMENT '企业备注',
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='企业';

CREATE TABLE `mg_exchange_rates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `rate_date` date NOT NULL COMMENT 'CurrencyAPI 汇率快照对应的 UTC 日期',
  `base_currency_code` varchar(16) NOT NULL DEFAULT 'USD' COMMENT 'CurrencyAPI 返回结果的基准币种',
  `rate_json` json NOT NULL COMMENT '当日完整汇率 JSON',
  `source` varchar(32) NOT NULL COMMENT '汇率数据来源',
  `source_update_time` datetime(3) NOT NULL COMMENT 'CurrencyAPI 声明的 UTC 数据更新时间',
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_date_base_source` (`rate_date`,`base_currency_code`,`source`),
  KEY `idx_source_time` (`source`,`source_update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='每日汇率快照';

CREATE TABLE `mg_game_brands` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `platform_code` varchar(32) NOT NULL COMMENT '游戏平台编码',
  `provider_brand_code` varchar(64) NOT NULL COMMENT '上游品牌编码',
  `unique_brand_id` bigint unsigned DEFAULT NULL COMMENT '归并后的统一品牌 ID',
  `mapping_status` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '归并状态：0待归并，1自动归并，2人工归并',
  `mapped_by` bigint unsigned DEFAULT NULL COMMENT '人工归并管理员 ID',
  `mapped_time` datetime(3) DEFAULT NULL COMMENT 'UTC 归并时间',
  `is_gc` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否支持美国市场 SC 和 GC 钱包',
  `name` varchar(150) NOT NULL COMMENT '上游品牌默认名称',
  `names` json DEFAULT NULL COMMENT '上游品牌多语言名称',
  `logo_url` varchar(500) DEFAULT NULL COMMENT '品牌图标地址',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序值，越小越靠前',
  `status` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '状态：0停用，1启用',
  `last_sync_time` datetime(3) DEFAULT NULL COMMENT 'UTC 最近同步时间',
  `extra` json DEFAULT NULL COMMENT '上游扩展数据',
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_platform_brand` (`platform_code`,`provider_brand_code`),
  KEY `idx_unique_brand` (`unique_brand_id`,`status`),
  KEY `idx_mapping_status` (`mapping_status`,`platform_code`),
  KEY `idx_status_sort` (`status`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='游戏平台品牌资源';

CREATE TABLE `mg_games` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `game_code` varchar(96) DEFAULT NULL COMMENT 'MG 全局游戏编码：小写统一品牌编码_MG游戏标识',
  `brand_id` bigint unsigned NOT NULL COMMENT '品牌资源 ID',
  `platform_code` varchar(32) NOT NULL COMMENT '游戏平台编码',
  `provider_game_code` varchar(128) NOT NULL COMMENT '上游游戏编码',
  `name` varchar(150) NOT NULL COMMENT '游戏默认名称',
  `names` json DEFAULT NULL COMMENT '游戏多语言名称',
  `icon_url` varchar(500) DEFAULT NULL COMMENT '游戏图标地址',
  `currency_codes` json NOT NULL COMMENT '上游支持的钱包编码',
  `support_demo` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否支持试玩',
  `support_rtp` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否支持设置 RTP',
  `rtp_options` json DEFAULT NULL COMMENT '上游可选 RTP',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序值，越小越靠前',
  `status` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '状态：0停用，1启用',
  `last_sync_time` datetime(3) DEFAULT NULL COMMENT 'UTC 最近同步时间',
  `extra` json DEFAULT NULL COMMENT '上游扩展数据',
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_provider_game` (`platform_code`,`brand_id`,`provider_game_code`),
  UNIQUE KEY `uk_game_code` (`game_code`),
  KEY `idx_brand_status` (`brand_id`,`status`),
  KEY `idx_platform_status` (`platform_code`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='游戏资源';

CREATE TABLE `mg_hourly_stats` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `merchant_id` bigint unsigned NOT NULL COMMENT '统计范围；0 为平台口径，其他为商户 ID',
  `timezone` varchar(64) NOT NULL COMMENT '当前小时统计行采用的 IANA 时区快照',
  `stat_date` date NOT NULL COMMENT '按本行 timezone 计算的自然日',
  `stat_hour` tinyint unsigned NOT NULL COMMENT '按本行 timezone 计算的小时，范围 0-23',
  `active_user_count` bigint unsigned NOT NULL DEFAULT '0' COMMENT '成功下注去重玩家数',
  `bet_count` bigint unsigned NOT NULL DEFAULT '0' COMMENT '成功注单量',
  `bet_amounts` json NOT NULL COMMENT '各业务钱包原始下注额 JSON',
  `converted_currency_code` varchar(16) NOT NULL COMMENT '统计行折算币种快照',
  `converted_bet_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '折算后的可计价下注总额',
  `exchange_rate_id` bigint unsigned DEFAULT NULL COMMENT '平台统计采用的汇率快照 ID',
  `exchange_rate_values` json DEFAULT NULL COMMENT '各原始钱包实际采用的换算值 JSON',
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scope_hour` (`merchant_id`,`stat_date`,`stat_hour`),
  KEY `idx_date_scope` (`stat_date`,`merchant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='小时流量统计';

CREATE TABLE `mg_merchant_bills` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `bill_no` varchar(40) NOT NULL COMMENT '商户流水号',
  `credit_id` bigint unsigned NOT NULL COMMENT '商户币种额度 ID',
  `type` tinyint unsigned NOT NULL COMMENT '流水类型：1充值，2服务费，3人工调整，4月费',
  `direction` tinyint unsigned NOT NULL COMMENT '资金方向：1增加，2减少',
  `amount` decimal(24,8) NOT NULL COMMENT '流水金额',
  `before_amount` decimal(24,8) NOT NULL COMMENT '变动前金额',
  `after_amount` decimal(24,8) NOT NULL COMMENT '变动后金额',
  `source` varchar(32) NOT NULL COMMENT '业务来源',
  `source_no` varchar(64) DEFAULT NULL COMMENT '来源业务编号',
  `data` json DEFAULT NULL COMMENT '业务快照',
  `remark` varchar(500) DEFAULT NULL COMMENT '流水备注',
  `created_by` bigint unsigned DEFAULT NULL,
  `create_time` datetime(3) NOT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bill_no` (`bill_no`),
  KEY `idx_credit_time` (`credit_id`,`create_time`),
  KEY `idx_source` (`source`,`source_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商户资金流水';

CREATE TABLE `mg_merchant_brands` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `merchant_id` bigint unsigned NOT NULL COMMENT '商户 ID',
  `unique_brand_id` bigint unsigned NOT NULL COMMENT '统一品牌 ID',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '平台授权状态：0关闭，1开启',
  `merchant_status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '企业上架状态：0关闭，1开启',
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_brand` (`merchant_id`,`unique_brand_id`),
  KEY `idx_brand_status` (`unique_brand_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商户品牌授权';

CREATE TABLE `mg_merchant_credits` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `merchant_id` bigint unsigned NOT NULL COMMENT '商户 ID',
  `currency_code` varchar(16) NOT NULL COMMENT '业务钱包编码',
  `rate_value` decimal(16,10) NOT NULL DEFAULT '0.0300000000' COMMENT '正 GGR 分成费率',
  `settlement_enabled` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '是否参与费用结算；GC 固定为 0',
  `available_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '可用服务费额度',
  `reserved_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '下注中预留服务费额度',
  `payable_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '已产生待支付费用',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '状态：0停用，1启用',
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_currency` (`merchant_id`,`currency_code`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商户币种额度';

CREATE TABLE `mg_merchant_games` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `merchant_id` bigint unsigned NOT NULL COMMENT '商户 ID',
  `game_id` bigint unsigned NOT NULL COMMENT '游戏资源 ID',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '平台授权状态：0关闭，1开启',
  `merchant_status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '企业上架状态：0关闭，1开启',
  `rate_value` decimal(16,10) DEFAULT NULL COMMENT '此游戏覆盖的 GGR 费率',
  `default_rtp` varchar(16) DEFAULT NULL COMMENT '此商户下游戏默认 RTP',
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_game` (`merchant_id`,`game_id`),
  KEY `idx_game_status` (`game_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商户游戏授权';

CREATE TABLE `mg_merchant_monthly_bills` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `bill_no` varchar(40) NOT NULL COMMENT '阶梯月费账单号',
  `merchant_id` bigint unsigned NOT NULL COMMENT '商户 ID',
  `billing_month` date NOT NULL COMMENT '收费月份，保存当月第一天',
  `source_month` date DEFAULT NULL COMMENT '阶梯计算来源月份；首月为空',
  `metric_type` tinyint unsigned NOT NULL COMMENT '阶梯指标：1月投注额，2月注单量',
  `metric_value` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '来源月份指标值',
  `amount` decimal(24,8) NOT NULL COMMENT '本月应付金额，单位 U',
  `status` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '状态：0待支付，1已支付，2已逾期，3已减免',
  `rules_snapshot` json NOT NULL COMMENT '出账时阶梯规则快照',
  `paid_time` datetime(3) DEFAULT NULL COMMENT 'UTC 支付或减免时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '账单备注',
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bill_no` (`bill_no`),
  UNIQUE KEY `uk_merchant_month` (`merchant_id`,`billing_month`),
  KEY `idx_month_status` (`billing_month`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商户阶梯月费账单';

CREATE TABLE `mg_merchant_monthly_usages` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `credit_id` bigint unsigned NOT NULL COMMENT '商户币种额度 ID',
  `billing_month` date NOT NULL COMMENT '商户时区计费月份，保存当月第一天',
  `bet_count` bigint unsigned NOT NULL DEFAULT '0' COMMENT '已结算有效注单量',
  `billed_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '已确认服务费',
  `reserved_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '下注中预留服务费',
  `rules_snapshot` json NOT NULL COMMENT '计费方式和费率快照',
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_credit_month` (`credit_id`,`billing_month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商户月度计费用量';

CREATE TABLE `mg_merchants` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `enterprise_id` bigint unsigned NOT NULL COMMENT '企业 ID',
  `mch_id` varchar(32) DEFAULT NULL COMMENT '商户接入编号；创建后根据自增 ID 回写',
  `name` varchar(100) NOT NULL COMMENT '商户名称',
  `wallet_mode` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '钱包模式：1单一钱包，2转账钱包',
  `callback_url` varchar(255) DEFAULT NULL COMMENT '商户通知基础地址',
  `secret` varchar(255) NOT NULL COMMENT '商户签名密钥密文',
  `ip_whitelist` json DEFAULT NULL COMMENT '允许调用接口的 IP 列表',
  `language_codes` json NOT NULL COMMENT '支持的语言编码',
  `default_language` varchar(16) NOT NULL DEFAULT 'en' COMMENT '默认语言编码',
  `gc_exchange_rate` decimal(20,8) NOT NULL DEFAULT '10000.00000000' COMMENT '充值 1 USD 发放的 GC 数量；GC 无财务价值',
  `billing_mode` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '计费方案：1正 GGR 分成，2阶梯月费',
  `monthly_metric` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '月费阶梯指标：1月投注额，2月注单量',
  `monthly_min_fee` decimal(24,8) NOT NULL DEFAULT '1000.00000000' COMMENT '首月及阶梯最低月费，单位 U',
  `monthly_tiers` json DEFAULT NULL COMMENT '月费阶梯规则，按起始值升序',
  `timezone` varchar(64) NOT NULL DEFAULT 'UTC' COMMENT '商户业务 IANA 时区；用于营业日、月费账期和商户后台时间展示',
  `timeout_ms` int unsigned NOT NULL DEFAULT '5000' COMMENT '调用商户回调超时毫秒数',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '状态：0停用，1启用',
  `remark` varchar(500) DEFAULT NULL COMMENT '商户备注',
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mch_id` (`mch_id`),
  KEY `idx_enterprise_status` (`enterprise_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商户接入参数';

CREATE TABLE `mg_monthly_stats` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `merchant_id` bigint unsigned NOT NULL COMMENT '统计范围；0 为平台口径，其他为商户 ID',
  `timezone` varchar(64) NOT NULL COMMENT '当前月度统计行采用的 IANA 时区快照',
  `stat_month` char(7) NOT NULL COMMENT '按本行 timezone 计算的自然月，格式 YYYY-MM',
  `active_user_count` bigint unsigned NOT NULL DEFAULT '0' COMMENT '成功下注去重玩家数',
  `bet_count` bigint unsigned NOT NULL DEFAULT '0' COMMENT '成功注单量',
  `bet_amounts` json NOT NULL COMMENT '各业务钱包原始下注额 JSON',
  `converted_currency_code` varchar(16) NOT NULL COMMENT '统计行折算币种快照',
  `converted_bet_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '折算后的可计价下注总额',
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scope_month` (`merchant_id`,`stat_month`),
  KEY `idx_month_scope` (`stat_month`,`merchant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='月度访问统计';

CREATE TABLE `mg_unique_brands` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(64) NOT NULL COMMENT '全局唯一品牌编码',
  `name` varchar(150) NOT NULL COMMENT '品牌默认名称',
  `names` json DEFAULT NULL COMMENT '品牌多语言名称',
  `logo_url` varchar(500) DEFAULT NULL COMMENT '品牌图标地址',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序值，越小越靠前',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '状态：0停用，1启用',
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code` (`code`),
  KEY `idx_status_sort` (`status`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='统一品牌';

CREATE TABLE `mg_user_game_rtps` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `merchant_id` bigint unsigned NOT NULL COMMENT '商户 ID',
  `user_id` bigint unsigned NOT NULL COMMENT '玩家 ID',
  `game_id` bigint unsigned NOT NULL COMMENT '游戏资源 ID',
  `currency_code` varchar(16) NOT NULL COMMENT '业务钱包编码',
  `rtp` varchar(16) NOT NULL COMMENT '玩家游戏 RTP',
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_game_currency` (`merchant_id`,`user_id`,`game_id`,`currency_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='玩家游戏 RTP';

CREATE TABLE `mg_users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `merchant_id` bigint unsigned NOT NULL COMMENT '商户 ID',
  `merchant_user_id` varchar(64) NOT NULL COMMENT '商户玩家标识',
  `nickname` varchar(100) DEFAULT NULL COMMENT '玩家昵称',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '状态：0停用，1启用',
  `last_launch_time` datetime(3) DEFAULT NULL COMMENT 'UTC 最近进入游戏时间',
  `last_ip` varchar(45) DEFAULT NULL COMMENT '最近进入游戏 IP',
  `extra` json DEFAULT NULL COMMENT '商户扩展数据',
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_user` (`merchant_id`,`merchant_user_id`),
  KEY `idx_merchant_status_id` (`merchant_id`,`status`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商户玩家';

CREATE TABLE `sa_system_attachment` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `category_id` int DEFAULT '0' COMMENT '文件分类',
  `storage_mode` smallint DEFAULT '1' COMMENT '存储模式 (1 本地 2 阿里云 3 七牛云 4 腾讯云)',
  `origin_name` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '原文件名',
  `object_name` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '新文件名',
  `hash` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '文件hash',
  `mime_type` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '资源类型',
  `storage_path` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '存储目录',
  `suffix` varchar(10) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '文件后缀',
  `size_byte` bigint DEFAULT NULL COMMENT '字节数',
  `size_info` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '文件大小',
  `url` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'url地址',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `created_by` int DEFAULT NULL COMMENT '创建者',
  `updated_by` int DEFAULT NULL COMMENT '更新者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `hash` (`hash`) USING BTREE,
  KEY `idx_url` (`url`) USING BTREE,
  KEY `idx_create_time` (`create_time`) USING BTREE,
  KEY `idx_category_id` (`category_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='附件信息表';

CREATE TABLE `sa_system_category` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '分类ID',
  `parent_id` int NOT NULL DEFAULT '0' COMMENT '父id',
  `level` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '组集关系',
  `category_name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '分类名称',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `created_by` int DEFAULT NULL COMMENT '创建者',
  `updated_by` int DEFAULT NULL COMMENT '更新者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `pid` (`parent_id`) USING BTREE,
  KEY `sort` (`sort`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='附件分类表';

CREATE TABLE `sa_system_config` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '编号',
  `group_id` int DEFAULT NULL COMMENT '组id',
  `key` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '配置键名',
  `value` text COLLATE utf8mb4_general_ci COMMENT '配置值',
  `name` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '配置名称',
  `input_type` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '数据输入类型',
  `config_select_data` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '配置选项数据',
  `sort` smallint unsigned DEFAULT '0' COMMENT '排序',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `created_by` int DEFAULT NULL COMMENT '创建人',
  `updated_by` int DEFAULT NULL COMMENT '更新人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`,`key`) USING BTREE,
  KEY `group_id` (`group_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='参数配置信息表';

CREATE TABLE `sa_system_config_group` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '字典名称',
  `code` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '字典标示',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `created_by` int DEFAULT NULL COMMENT '创建人',
  `updated_by` int DEFAULT NULL COMMENT '更新人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='参数配置分组表';

CREATE TABLE `sa_system_dept` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` bigint unsigned DEFAULT '0' COMMENT '父级ID，0为根节点',
  `name` varchar(64) COLLATE utf8mb4_general_ci NOT NULL COMMENT '部门名称',
  `code` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '部门编码',
  `leader_id` bigint unsigned DEFAULT NULL COMMENT '部门负责人ID',
  `level` varchar(255) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '祖级列表，格式: 0,1,5, (便于查询子孙节点)',
  `sort` int DEFAULT '0' COMMENT '排序，数字越小越靠前',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态: 1启用, 0禁用',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `created_by` int DEFAULT NULL COMMENT '创建者',
  `updated_by` int DEFAULT NULL COMMENT '更新者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_parent_id` (`parent_id`) USING BTREE,
  KEY `idx_path` (`level`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='部门表';

CREATE TABLE `sa_system_dict_data` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `type_id` int unsigned DEFAULT NULL COMMENT '字典类型ID',
  `label` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '字典标签',
  `value` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '字典值',
  `color` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '字典颜色',
  `code` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '字典标示',
  `sort` smallint unsigned DEFAULT '0' COMMENT '排序',
  `status` smallint DEFAULT '1' COMMENT '状态 (1正常 2停用)',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `created_by` int DEFAULT NULL COMMENT '创建者',
  `updated_by` int DEFAULT NULL COMMENT '更新者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `type_id` (`type_id`) USING BTREE,
  KEY `idx_code` (`code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='字典数据表';

CREATE TABLE `sa_system_dict_type` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '字典名称',
  `code` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '字典标示',
  `status` smallint DEFAULT '1' COMMENT '状态 (1正常 2停用)',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `created_by` int DEFAULT NULL COMMENT '创建者',
  `updated_by` int DEFAULT NULL COMMENT '更新者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_code` (`code`) USING BTREE,
  KEY `idx_name` (`name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='字典类型表';

CREATE TABLE `sa_system_login_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `username` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '用户名',
  `ip` varchar(45) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '登录IP地址',
  `ip_location` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'IP所属地',
  `os` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '操作系统',
  `browser` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '浏览器',
  `status` smallint DEFAULT '1' COMMENT '登录状态 (1成功 2失败)',
  `message` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '提示消息',
  `login_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '登录时间',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `created_by` int DEFAULT NULL COMMENT '创建者',
  `updated_by` int DEFAULT NULL COMMENT '更新者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `username` (`username`) USING BTREE,
  KEY `idx_create_time` (`create_time`) USING BTREE,
  KEY `idx_login_time` (`login_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='登录日志表';

CREATE TABLE `sa_system_mail` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '编号',
  `gateway` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '网关',
  `from` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '发送人',
  `email` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '接收人',
  `code` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '验证码',
  `content` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '邮箱内容',
  `status` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '发送状态',
  `response` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '返回结果',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_create_time` (`create_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='邮件记录';

CREATE TABLE `sa_system_menu` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` bigint unsigned DEFAULT '0' COMMENT '父级ID',
  `name` varchar(64) COLLATE utf8mb4_general_ci NOT NULL COMMENT '菜单名称',
  `code` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '组件名称',
  `slug` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '权限标识，如 user:list, user:add',
  `type` tinyint(1) NOT NULL DEFAULT '1' COMMENT '类型: 1目录, 2菜单, 3按钮/API',
  `path` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '路由地址(前端)或API路径(后端)',
  `component` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '前端组件路径，如 layout/User',
  `method` varchar(10) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '请求方式',
  `icon` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '图标',
  `sort` int DEFAULT '100' COMMENT '排序',
  `link_url` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '外部链接',
  `is_iframe` tinyint(1) DEFAULT '2' COMMENT '是否iframe',
  `is_keep_alive` tinyint(1) DEFAULT '2' COMMENT '是否缓存',
  `is_hidden` tinyint(1) DEFAULT '2' COMMENT '是否隐藏',
  `is_fixed_tab` tinyint(1) DEFAULT '2' COMMENT '是否固定标签页',
  `is_full_page` tinyint(1) DEFAULT '2' COMMENT '是否全屏',
  `generate_id` int DEFAULT '0' COMMENT '生成id',
  `generate_key` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '生成key',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `created_by` int DEFAULT NULL COMMENT '创建者',
  `updated_by` int DEFAULT NULL COMMENT '更新者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_parent_id` (`parent_id`) USING BTREE,
  KEY `idx_slug` (`slug`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='菜单权限表';

CREATE TABLE `sa_system_oper_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `username` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '用户名',
  `app` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '应用名称',
  `method` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '请求方式',
  `router` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '请求路由',
  `service_name` varchar(30) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '业务名称',
  `ip` varchar(45) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '请求IP地址',
  `ip_location` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'IP所属地',
  `request_data` text COLLATE utf8mb4_general_ci COMMENT '请求数据',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `created_by` int DEFAULT NULL COMMENT '创建者',
  `updated_by` int DEFAULT NULL COMMENT '更新者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `username` (`username`) USING BTREE,
  KEY `idx_create_time` (`create_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='操作日志表';

CREATE TABLE `sa_system_post` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '岗位名称',
  `code` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '岗位代码',
  `sort` smallint unsigned DEFAULT '0' COMMENT '排序',
  `status` smallint DEFAULT '1' COMMENT '状态 (1正常 2停用)',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `created_by` int DEFAULT NULL COMMENT '创建者',
  `updated_by` int DEFAULT NULL COMMENT '更新者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='岗位信息表';

CREATE TABLE `sa_system_role` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) COLLATE utf8mb4_general_ci NOT NULL COMMENT '角色名称',
  `code` varchar(64) COLLATE utf8mb4_general_ci NOT NULL COMMENT '角色标识(英文唯一)，如: hr_manager',
  `level` int DEFAULT '1' COMMENT '角色级别(1-100)：用于行政控制，不可操作级别>=自己的角色',
  `data_scope` tinyint DEFAULT '1' COMMENT '数据范围: 1全部, 2本部门及下属, 3本部门, 4仅本人, 5自定义',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `sort` int DEFAULT '100',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态: 1启用, 0禁用',
  `created_by` int DEFAULT NULL COMMENT '创建者',
  `updated_by` int DEFAULT NULL COMMENT '更新者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_slug` (`code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='角色表';

CREATE TABLE `sa_system_role_dept` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `role_id` bigint unsigned NOT NULL,
  `dept_id` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_role_id` (`role_id`) USING BTREE,
  KEY `idx_dept_id` (`dept_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='角色-自定义数据权限关联';

CREATE TABLE `sa_system_role_menu` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `role_id` bigint unsigned NOT NULL,
  `menu_id` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_menu_id` (`menu_id`) USING BTREE,
  KEY `idx_role_id` (`role_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='角色权限关联';

CREATE TABLE `sa_system_user` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(64) COLLATE utf8mb4_general_ci NOT NULL COMMENT '登录账号',
  `password` varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '加密密码',
  `realname` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '真实姓名',
  `gender` varchar(10) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '性别',
  `avatar` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '头像',
  `email` varchar(128) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '邮箱',
  `phone` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '手机号',
  `signed` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '个性签名',
  `dashboard` varchar(255) COLLATE utf8mb4_general_ci DEFAULT 'work' COMMENT '工作台',
  `dept_id` bigint unsigned DEFAULT NULL COMMENT '主归属部门',
  `is_super` tinyint(1) DEFAULT '0' COMMENT '是否超级管理员: 1是(跳过权限检查), 0否',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态: 1启用, 0禁用',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `login_time` timestamp NULL DEFAULT NULL COMMENT '最后登录时间',
  `login_ip` varchar(45) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '最后登录IP',
  `created_by` int DEFAULT NULL COMMENT '创建者',
  `updated_by` int DEFAULT NULL COMMENT '更新者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_username` (`username`) USING BTREE,
  KEY `idx_dept_id` (`dept_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='用户表';

CREATE TABLE `sa_system_user_post` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` bigint unsigned NOT NULL COMMENT '用户主键',
  `post_id` bigint unsigned NOT NULL COMMENT '岗位主键',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_user_id` (`user_id`) USING BTREE,
  KEY `idx_post_id` (`post_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='用户与岗位关联表';

CREATE TABLE `sa_system_user_role` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `role_id` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_role_id` (`role_id`) USING BTREE,
  KEY `idx_user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='用户角色关联';

CREATE TABLE `sa_tool_crontab` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '任务名称',
  `type` smallint DEFAULT '4' COMMENT '任务类型',
  `target` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '调用任务字符串',
  `parameter` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '调用任务参数',
  `task_style` tinyint(1) DEFAULT NULL COMMENT '执行类型',
  `rule` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '任务执行表达式',
  `singleton` smallint DEFAULT '1' COMMENT '是否单次执行 (1 是 2 不是)',
  `status` smallint DEFAULT '1' COMMENT '状态 (1正常 2停用)',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `created_by` int DEFAULT NULL COMMENT '创建者',
  `updated_by` int DEFAULT NULL COMMENT '更新者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='定时任务信息表';

CREATE TABLE `sa_tool_crontab_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `crontab_id` int unsigned DEFAULT NULL COMMENT '任务ID',
  `name` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '任务名称',
  `target` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '任务调用目标字符串',
  `parameter` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '任务调用参数',
  `exception_info` varchar(2000) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '异常信息',
  `status` smallint DEFAULT '1' COMMENT '执行状态 (1成功 2失败)',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='定时任务执行日志表';

CREATE TABLE `sa_tool_generate_columns` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `table_id` int unsigned DEFAULT NULL COMMENT '所属表ID',
  `column_name` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '字段名称',
  `column_comment` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '字段注释',
  `column_type` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '字段类型',
  `default_value` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '默认值',
  `is_pk` smallint DEFAULT '1' COMMENT '1 非主键 2 主键',
  `is_required` smallint DEFAULT '1' COMMENT '1 非必填 2 必填',
  `is_insert` smallint DEFAULT '1' COMMENT '1 非插入字段 2 插入字段',
  `is_edit` smallint DEFAULT '1' COMMENT '1 非编辑字段 2 编辑字段',
  `is_list` smallint DEFAULT '1' COMMENT '1 非列表显示字段 2 列表显示字段',
  `is_query` smallint DEFAULT '1' COMMENT '1 非查询字段 2 查询字段',
  `is_sort` smallint DEFAULT '1' COMMENT '1 非排序 2 排序',
  `query_type` varchar(100) COLLATE utf8mb4_general_ci DEFAULT 'eq' COMMENT '查询方式 eq 等于, neq 不等于, gt 大于, lt 小于, like 范围',
  `view_type` varchar(100) COLLATE utf8mb4_general_ci DEFAULT 'text' COMMENT '页面控件,text, textarea, password, select, checkbox, radio, date, upload, ma-upload(封装的上传控件)',
  `dict_type` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '字典类型',
  `allow_roles` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '允许查看该字段的角色',
  `options` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '字段其他设置',
  `sort` tinyint unsigned DEFAULT '0' COMMENT '排序',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `created_by` int DEFAULT NULL COMMENT '创建者',
  `updated_by` int DEFAULT NULL COMMENT '更新者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='代码生成业务字段表';

CREATE TABLE `sa_tool_generate_tables` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `table_name` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '表名称',
  `table_comment` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '表注释',
  `stub` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'stub类型',
  `template` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '模板名称',
  `namespace` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '命名空间',
  `package_name` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '控制器包名',
  `business_name` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '业务名称',
  `class_name` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '类名称',
  `menu_name` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '生成菜单名',
  `belong_menu_id` int DEFAULT NULL COMMENT '所属菜单',
  `tpl_category` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '生成类型,single 单表CRUD,tree 树表CRUD,parent_sub父子表CRUD',
  `generate_type` smallint DEFAULT '1' COMMENT '1 压缩包下载 2 生成到模块',
  `generate_path` varchar(100) COLLATE utf8mb4_general_ci DEFAULT 'saiadmin-artd' COMMENT '前端根目录',
  `generate_model` smallint DEFAULT '1' COMMENT '1 软删除 2 非软删除',
  `generate_menus` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '生成菜单列表',
  `build_menu` smallint DEFAULT '1' COMMENT '是否构建菜单',
  `component_type` smallint DEFAULT '1' COMMENT '组件显示方式',
  `options` varchar(1500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '其他业务选项',
  `form_width` int DEFAULT '800' COMMENT '表单宽度',
  `is_full` tinyint(1) DEFAULT '1' COMMENT '是否全屏',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `source` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '数据源',
  `created_by` int DEFAULT NULL COMMENT '创建者',
  `updated_by` int DEFAULT NULL COMMENT '更新者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='代码生成业务表';

CREATE TABLE `mgs_configs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `type` varchar(32) NOT NULL COMMENT 'MGS 配置分组',
  `code` varchar(64) NOT NULL COMMENT 'MGS 配置编码',
  `name` varchar(100) NOT NULL COMMENT '配置名称',
  `value` json NOT NULL COMMENT '配置值 JSON',
  `remark` varchar(500) DEFAULT NULL COMMENT '运营说明',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '状态：0停用，1启用',
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code` (`code`),
  KEY `idx_type_status` (`type`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MGS 自营平台配置';

CREATE TABLE `mgs_brands` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `platform` varchar(32) NOT NULL DEFAULT 'mgames' COMMENT '游戏平台来源编码',
  `platform_brand_code` varchar(64) NOT NULL COMMENT '游戏平台品牌编码',
  `name` varchar(150) NOT NULL COMMENT '品牌名称',
  `names` json DEFAULT NULL COMMENT '品牌多语言名称',
  `logo_url` varchar(500) DEFAULT NULL COMMENT '品牌图标地址',
  `sort` int NOT NULL DEFAULT '0' COMMENT 'MGS 展示排序',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT 'MGS 状态：0停用，1启用',
  `last_sync_time` datetime(3) DEFAULT NULL COMMENT 'UTC 最近同步时间',
  `extra` json DEFAULT NULL COMMENT '游戏平台扩展快照',
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_platform_brand` (`platform`,`platform_brand_code`),
  KEY `idx_status_sort` (`status`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MGS 品牌快照';

CREATE TABLE `mgs_games` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `sort` int NOT NULL DEFAULT '0' COMMENT 'MGS 展示排序',
  `platform` varchar(32) NOT NULL DEFAULT 'mgames' COMMENT '游戏平台来源编码',
  `brand_id` bigint unsigned NOT NULL COMMENT 'MGS 品牌 ID',
  `platform_brand_code` varchar(64) NOT NULL COMMENT '游戏平台品牌编码快照',
  `platform_game_id` varchar(128) NOT NULL COMMENT '游戏平台游戏主键快照',
  `platform_game_code` varchar(128) NOT NULL COMMENT '游戏平台游戏编码快照',
  `real_game_code` varchar(128) DEFAULT NULL COMMENT '游戏平台实际游戏编码快照',
  `name` varchar(150) NOT NULL COMMENT '游戏名称',
  `names` json DEFAULT NULL COMMENT '游戏多语言名称',
  `icon_url` varchar(500) DEFAULT NULL COMMENT '游戏图标地址',
  `banner_url` varchar(500) DEFAULT NULL COMMENT '游戏横幅地址',
  `game_type` varchar(32) DEFAULT NULL COMMENT '游戏类型',
  `currency_codes` json NOT NULL COMMENT '游戏平台支持币种 JSON',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT 'MGS 状态：0停用，1启用',
  `is_hot` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否热门',
  `is_new` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否新品',
  `support_rtp` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否支持 RTP',
  `rtp_options` json DEFAULT NULL COMMENT 'RTP 可选值 JSON',
  `default_rtp` varchar(16) DEFAULT NULL COMMENT 'MGS 默认 RTP',
  `rate_value` decimal(16,10) NOT NULL DEFAULT '0.0000000000' COMMENT 'MGS 与游戏平台约定费率',
  `last_sync_time` datetime(3) DEFAULT NULL COMMENT 'UTC 最近同步时间',
  `extra` json DEFAULT NULL COMMENT '游戏平台扩展快照',
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_platform_game` (`platform`,`platform_game_id`),
  KEY `idx_brand_status` (`brand_id`,`status`),
  KEY `idx_platform_status` (`platform`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MGS 自营游戏';

CREATE TABLE `mgs_users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_no` varchar(128) NOT NULL COMMENT 'C 端业务用户编号',
  `nickname` varchar(150) DEFAULT NULL COMMENT '用户昵称，可选',
  `language` varchar(16) NOT NULL DEFAULT 'en' COMMENT '用户语言编码',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '状态：0停用，1启用',
  `last_login_time` datetime(3) DEFAULT NULL COMMENT 'UTC 最近登录时间',
  `last_launch_time` datetime(3) DEFAULT NULL COMMENT 'UTC 最近进游时间',
  `last_ip` varchar(64) DEFAULT NULL COMMENT '最近访问 IP',
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_no` (`user_no`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MGS C 端用户';

CREATE TABLE `mgs_wallets` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL COMMENT 'MGS 用户 ID',
  `currency_code` varchar(16) NOT NULL COMMENT '钱包币种编码',
  `balance` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '当前余额',
  `version` bigint unsigned NOT NULL DEFAULT '0' COMMENT '余额版本号',
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_currency` (`user_id`,`currency_code`),
  KEY `idx_currency_balance` (`currency_code`,`balance`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MGS 用户余额快照';

CREATE TABLE `mgs_bets_template` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `bet_no` varchar(40) NOT NULL COMMENT 'MGS 注单号，包含 UTC 创建日期',
  `user_id` bigint unsigned NOT NULL COMMENT 'MGS 用户 ID',
  `game_id` bigint unsigned NOT NULL COMMENT 'MGS 游戏 ID',
  `currency_code` varchar(16) NOT NULL COMMENT '业务钱包编码',
  `round_key` char(64) NOT NULL COMMENT '游戏平台对局幂等键 SHA-256',
  `platform_round_id` varchar(128) NOT NULL COMMENT '游戏平台局号',
  `bet_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '累计下注额',
  `bet_rollback_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '累计下注回滚额',
  `win_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '累计派奖额',
  `win_rollback_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '累计派奖回滚额',
  `ggr_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '原始 GGR，可为负数',
  `rtp_value` decimal(16,10) DEFAULT NULL COMMENT '注单最终 RTP',
  `rate_value` decimal(16,10) NOT NULL DEFAULT '0.0000000000' COMMENT '费率快照',
  `platform_fee` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '游戏平台服务费',
  `actions` json DEFAULT NULL COMMENT '对局资金动作摘要',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '状态：1进行中，2已结单，3已取消，4异常',
  `business_date` date NOT NULL COMMENT 'MGS 时区营业日期',
  `platform_date` date NOT NULL COMMENT 'MGS 平台统计日期',
  `settled_time` datetime(3) DEFAULT NULL COMMENT 'UTC 最终结单时间',
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bet_no` (`bet_no`),
  UNIQUE KEY `uk_round_key` (`round_key`),
  KEY `idx_user_date` (`user_id`,`business_date`,`id`),
  KEY `idx_game_date` (`game_id`,`business_date`,`id`),
  KEY `idx_status_time` (`status`,`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MGS 注单月表模板';

CREATE TABLE `mgs_bills_template` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `bill_no` varchar(40) NOT NULL COMMENT 'MGS 用户流水号，包含 UTC 创建日期',
  `bet_no` varchar(40) DEFAULT NULL COMMENT '关联 MGS 注单号',
  `user_id` bigint unsigned NOT NULL COMMENT 'MGS 用户 ID',
  `game_id` bigint unsigned DEFAULT NULL COMMENT 'MGS 游戏 ID',
  `type` varchar(24) NOT NULL COMMENT '流水类型：bet、win、cancel、rollback、adjust',
  `direction` tinyint unsigned NOT NULL COMMENT '资金方向：1增加，2减少',
  `transaction_id` varchar(128) NOT NULL COMMENT '游戏平台交易号',
  `original_transaction_id` varchar(128) DEFAULT NULL COMMENT '原交易号',
  `amount` decimal(24,8) NOT NULL COMMENT '流水金额',
  `currency_code` varchar(16) NOT NULL COMMENT '流水币种编码',
  `before_balance` decimal(24,8) NOT NULL COMMENT '变动前余额',
  `after_balance` decimal(24,8) NOT NULL COMMENT '变动后余额',
  `status` tinyint unsigned NOT NULL DEFAULT '2' COMMENT '状态：1处理中，2成功，3失败，4未知',
  `request_hash` char(64) NOT NULL COMMENT '规范化请求 SHA-256',
  `data` json DEFAULT NULL COMMENT '请求和结果摘要',
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bill_no` (`bill_no`),
  UNIQUE KEY `uk_user_currency_transaction` (`user_id`,`currency_code`,`transaction_id`,`type`),
  KEY `idx_user_time` (`user_id`,`create_time`,`id`),
  KEY `idx_bet` (`bet_no`,`id`),
  KEY `idx_status_time` (`status`,`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MGS 用户流水月表模板';

CREATE TABLE `mgs_daily_stats` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `stat_date` date NOT NULL COMMENT '按 MGS 平台时区计算的自然日',
  `game_id` bigint unsigned NOT NULL COMMENT 'MGS 游戏 ID',
  `currency_code` varchar(16) NOT NULL COMMENT '统计币种',
  `active_user_count` bigint unsigned NOT NULL DEFAULT '0' COMMENT '成功下注去重用户数',
  `bet_count` bigint unsigned NOT NULL DEFAULT '0' COMMENT '注单量',
  `bet_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '下注额',
  `win_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '派奖额',
  `rollback_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '回滚额',
  `ggr_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT 'GGR',
  `platform_fee` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '游戏平台服务费',
  `rtp_value` decimal(16,10) DEFAULT NULL COMMENT '返奖率',
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_date_game_currency` (`stat_date`,`game_id`,`currency_code`),
  KEY `idx_date` (`stat_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MGS 游戏日报';

CREATE TABLE `mgs_hourly_stats` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `stat_date` date NOT NULL COMMENT '按 MGS 平台时区计算的自然日',
  `stat_hour` tinyint unsigned NOT NULL COMMENT 'MGS 平台时区小时 0-23',
  `currency_code` varchar(16) NOT NULL COMMENT '统计币种',
  `active_user_count` bigint unsigned NOT NULL DEFAULT '0' COMMENT '成功下注去重用户数',
  `bet_count` bigint unsigned NOT NULL DEFAULT '0' COMMENT '注单量',
  `bet_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '下注额',
  `win_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '派奖额',
  `rollback_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '下注和派奖回滚额',
  `ggr_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT 'GGR',
  `platform_fee` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '游戏平台服务费',
  `rtp_value` decimal(16,10) DEFAULT NULL COMMENT '返奖率',
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_date_hour_currency` (`stat_date`,`stat_hour`,`currency_code`),
  KEY `idx_date_hour` (`stat_date`,`stat_hour`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MGS 小时趋势';

CREATE TABLE `mgs_monthly_stats` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `stat_month` char(7) NOT NULL COMMENT '按 MGS 平台时区计算的月份 YYYY-MM',
  `currency_code` varchar(16) NOT NULL COMMENT '统计币种',
  `active_user_count` bigint unsigned NOT NULL DEFAULT '0' COMMENT '成功下注去重用户数',
  `bet_count` bigint unsigned NOT NULL DEFAULT '0' COMMENT '注单量',
  `bet_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '下注额',
  `win_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '派奖额',
  `rollback_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '下注和派奖回滚额',
  `ggr_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT 'GGR',
  `platform_fee` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '游戏平台服务费',
  `rtp_value` decimal(16,10) DEFAULT NULL COMMENT '返奖率',
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_month_currency` (`stat_month`,`currency_code`),
  KEY `idx_month` (`stat_month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MGS 月度趋势';

CREATE TABLE `mgs_settlements` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `settlement_no` varchar(40) NOT NULL COMMENT 'MGS 部门结算单号',
  `settlement_month` char(7) NOT NULL COMMENT '结算月份 YYYY-MM',
  `currency_code` varchar(16) NOT NULL COMMENT '结算币种',
  `bet_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '下注额',
  `win_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '派奖额',
  `ggr_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT 'GGR',
  `rate_value` decimal(16,10) NOT NULL DEFAULT '0.0000000000' COMMENT '服务费率',
  `platform_fee` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '游戏平台服务费',
  `mgs_net_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT 'MGS 净额',
  `exchange_rate_id` bigint unsigned DEFAULT NULL COMMENT '实际采用的汇率快照 ID',
  `exchange_rate_value` decimal(36,18) DEFAULT NULL COMMENT '实际采用的换算值',
  `status` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '状态：0待确认，1已确认，2已支付',
  `paid_time` datetime(3) DEFAULT NULL COMMENT 'UTC 支付时间',
  `data` json DEFAULT NULL COMMENT '结算来源快照',
  `create_time` datetime(3) DEFAULT NULL,
  `update_time` datetime(3) DEFAULT NULL,
  `delete_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_settlement_currency` (`settlement_month`,`currency_code`),
  UNIQUE KEY `uk_settlement_no` (`settlement_no`),
  KEY `idx_status_month` (`status`,`settlement_month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MGS 与游戏平台部门结算';
