<?php

return array (
  'menus' =>
  array (
    0 =>
    array (
      'key' => 'Dashboard',
      'parent' => NULL,
      'name' => '仪表盘',
      'code' => 'Dashboard',
      'path' => '/dashboard',
      'icon' => 'ri:pie-chart-line',
    ),
    1 =>
    array (
      'key' => 'Console',
      'parent' => 'Dashboard',
      'name' => '工作台',
      'code' => 'Console',
      'type' => 2,
      'path' => 'console',
      'component' => '/dashboard/console',
      'icon' => 'ri:home-smile-2-line',
    ),
    2 =>
    array (
      'key' => 'System',
      'parent' => NULL,
      'name' => '系统管理',
      'code' => 'System',
      'path' => '/system',
      'icon' => 'ri:user-3-line',
    ),
    3 =>
    array (
      'key' => 'User',
      'parent' => 'System',
      'name' => '用户管理',
      'code' => 'User',
      'type' => 2,
      'path' => 'user',
      'component' => '/system/user',
      'icon' => 'ri:user-line',
    ),
    4 =>
    array (
      'key' => 'Dept',
      'parent' => 'System',
      'name' => '部门管理',
      'code' => 'Dept',
      'type' => 2,
      'path' => 'dept',
      'component' => '/system/dept',
      'icon' => 'ri:node-tree',
    ),
    5 =>
    array (
      'key' => 'Role',
      'parent' => 'System',
      'name' => '角色管理',
      'code' => 'Role',
      'type' => 2,
      'path' => 'role',
      'component' => '/system/role',
      'icon' => 'ri:admin-line',
    ),
    6 =>
    array (
      'key' => 'Post',
      'parent' => 'System',
      'name' => '岗位管理',
      'code' => 'Post',
      'slug' => '',
      'type' => 2,
      'path' => 'post',
      'component' => '/system/post',
      'icon' => 'ri:signpost-line',
      'link_url' => '',
    ),
    7 =>
    array (
      'key' => 'Menu',
      'parent' => 'System',
      'name' => '菜单管理',
      'code' => 'Menu',
      'type' => 2,
      'path' => 'menu',
      'component' => '/system/menu',
      'icon' => 'ri:menu-line',
    ),
    8 =>
    array (
      'key' => 'Safeguard',
      'parent' => NULL,
      'name' => '运维管理',
      'code' => 'Safeguard',
      'path' => '/safeguard',
      'component' => '',
      'icon' => 'ri:shield-check-line',
    ),
    9 =>
    array (
      'key' => 'Cache',
      'parent' => 'Safeguard',
      'name' => '缓存管理',
      'code' => 'Cache',
      'slug' => '',
      'type' => 2,
      'path' => 'cache',
      'component' => '/safeguard/cache',
      'icon' => 'ri:keyboard-box-line',
      'sort' => 80,
      'link_url' => '',
    ),
    10 =>
    array (
      'key' => 'Dict',
      'parent' => 'Safeguard',
      'name' => '数据字典',
      'code' => 'Dict',
      'type' => 2,
      'path' => 'dict',
      'component' => '/safeguard/dict',
      'icon' => 'ri:database-2-line',
    ),
    11 =>
    array (
      'key' => 'Attachment',
      'parent' => 'Safeguard',
      'name' => '附件管理',
      'code' => 'Attachment',
      'slug' => '',
      'type' => 2,
      'path' => 'attachment',
      'component' => '/safeguard/attachment',
      'icon' => 'ri:file-cloud-line',
      'link_url' => '',
    ),
    12 =>
    array (
      'key' => 'Database',
      'parent' => 'Safeguard',
      'name' => '数据表维护',
      'code' => 'Database',
      'slug' => '',
      'type' => 2,
      'path' => 'database',
      'component' => '/safeguard/database',
      'icon' => 'ri:database-line',
      'link_url' => '',
    ),
    13 =>
    array (
      'key' => 'LoginLog',
      'parent' => 'Safeguard',
      'name' => '登录日志',
      'code' => 'LoginLog',
      'slug' => '',
      'type' => 2,
      'path' => 'login-log',
      'component' => '/safeguard/login-log',
      'icon' => 'ri:login-circle-line',
      'sort' => 50,
      'link_url' => '',
    ),
    14 =>
    array (
      'key' => 'OperLog',
      'parent' => 'Safeguard',
      'name' => '操作日志',
      'code' => 'OperLog',
      'slug' => '',
      'type' => 2,
      'path' => 'oper-log',
      'component' => '/safeguard/oper-log',
      'icon' => 'ri:shield-keyhole-line',
      'sort' => 50,
      'link_url' => '',
    ),
    15 =>
    array (
      'key' => 'EmailLog',
      'parent' => 'Safeguard',
      'name' => '邮件日志',
      'code' => 'EmailLog',
      'slug' => '',
      'type' => 2,
      'path' => 'email-log',
      'component' => '/safeguard/email-log',
      'icon' => 'ri:mail-line',
      'sort' => 50,
      'link_url' => '',
    ),
    16 =>
    array (
      'key' => 'Config',
      'parent' => 'System',
      'name' => '系统设置',
      'code' => 'Config',
      'type' => 2,
      'path' => 'config',
      'component' => '/system/config',
      'icon' => 'ri:settings-4-line',
    ),
    17 =>
    array (
      'key' => 'Document',
      'parent' => 'MgGame',
      'name' => '对接文档',
      'code' => 'Document',
      'slug' => '',
      'type' => 2,
      'path' => 'document',
      'component' => '/game/document',
      'icon' => 'ri:file-copy-2-fill',
      'sort' => 0,
      'remark' => '',
    ),
    18 =>
    array (
      'key' => 'core:user:index',
      'parent' => 'User',
      'name' => '数据列表',
      'code' => '',
      'slug' => 'core:user:index',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    19 =>
    array (
      'key' => 'UserCenter',
      'parent' => 'Dashboard',
      'name' => '个人中心',
      'code' => 'UserCenter',
      'slug' => '',
      'type' => 2,
      'path' => 'user-center',
      'component' => '/dashboard/user-center/index',
      'icon' => 'ri:user-2-line',
      'link_url' => '',
      'is_hidden' => 1,
    ),
    20 =>
    array (
      'key' => 'core:user:save',
      'parent' => 'User',
      'name' => '添加',
      'code' => '',
      'slug' => 'core:user:save',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    21 =>
    array (
      'key' => 'core:user:update',
      'parent' => 'User',
      'name' => '修改',
      'code' => '',
      'slug' => 'core:user:update',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    22 =>
    array (
      'key' => 'core:user:read',
      'parent' => 'User',
      'name' => '读取',
      'code' => '',
      'slug' => 'core:user:read',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    23 =>
    array (
      'key' => 'core:user:destroy',
      'parent' => 'User',
      'name' => '删除',
      'code' => '',
      'slug' => 'core:user:destroy',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    24 =>
    array (
      'key' => 'core:user:password',
      'parent' => 'User',
      'name' => '重置密码',
      'code' => '',
      'slug' => 'core:user:password',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    25 =>
    array (
      'key' => 'core:user:cache',
      'parent' => 'User',
      'name' => '清理缓存',
      'code' => '',
      'slug' => 'core:user:cache',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    26 =>
    array (
      'key' => 'core:user:home',
      'parent' => 'User',
      'name' => '设置工作台',
      'code' => '',
      'slug' => 'core:user:home',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    27 =>
    array (
      'key' => 'core:dept:index',
      'parent' => 'Dept',
      'name' => '数据列表',
      'code' => '',
      'slug' => 'core:dept:index',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    28 =>
    array (
      'key' => 'core:dept:save',
      'parent' => 'Dept',
      'name' => '添加',
      'code' => '',
      'slug' => 'core:dept:save',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    29 =>
    array (
      'key' => 'core:dept:update',
      'parent' => 'Dept',
      'name' => '修改',
      'code' => '',
      'slug' => 'core:dept:update',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    30 =>
    array (
      'key' => 'core:dept:read',
      'parent' => 'Dept',
      'name' => '读取',
      'code' => '',
      'slug' => 'core:dept:read',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    31 =>
    array (
      'key' => 'core:dept:destroy',
      'parent' => 'Dept',
      'name' => '删除',
      'code' => '',
      'slug' => 'core:dept:destroy',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    32 =>
    array (
      'key' => 'core:role:save',
      'parent' => 'Role',
      'name' => '添加',
      'code' => '',
      'slug' => 'core:role:save',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    33 =>
    array (
      'key' => 'core:role:index',
      'parent' => 'Role',
      'name' => '数据列表',
      'code' => '',
      'slug' => 'core:role:index',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    34 =>
    array (
      'key' => 'core:role:update',
      'parent' => 'Role',
      'name' => '修改',
      'code' => '',
      'slug' => 'core:role:update',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    35 =>
    array (
      'key' => 'core:role:read',
      'parent' => 'Role',
      'name' => '读取',
      'code' => '',
      'slug' => 'core:role:read',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    36 =>
    array (
      'key' => 'core:role:destroy',
      'parent' => 'Role',
      'name' => '删除',
      'code' => '',
      'slug' => 'core:role:destroy',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    37 =>
    array (
      'key' => 'core:role:menu',
      'parent' => 'Role',
      'name' => '菜单权限',
      'code' => '',
      'slug' => 'core:role:menu',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    38 =>
    array (
      'key' => 'core:post:index',
      'parent' => 'Post',
      'name' => '数据列表',
      'code' => '',
      'slug' => 'core:post:index',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    39 =>
    array (
      'key' => 'core:post:save',
      'parent' => 'Post',
      'name' => '添加',
      'code' => '',
      'slug' => 'core:post:save',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    40 =>
    array (
      'key' => 'core:post:update',
      'parent' => 'Post',
      'name' => '修改',
      'code' => '',
      'slug' => 'core:post:update',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    41 =>
    array (
      'key' => 'core:post:read',
      'parent' => 'Post',
      'name' => '读取',
      'code' => '',
      'slug' => 'core:post:read',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    42 =>
    array (
      'key' => 'core:post:destroy',
      'parent' => 'Post',
      'name' => '删除',
      'code' => '',
      'slug' => 'core:post:destroy',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    43 =>
    array (
      'key' => 'core:post:import',
      'parent' => 'Post',
      'name' => '导入',
      'code' => '',
      'slug' => 'core:post:import',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    44 =>
    array (
      'key' => 'core:post:export',
      'parent' => 'Post',
      'name' => '导出',
      'code' => '',
      'slug' => 'core:post:export',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    45 =>
    array (
      'key' => 'core:menu:index',
      'parent' => 'Menu',
      'name' => '数据列表',
      'code' => '',
      'slug' => 'core:menu:index',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    46 =>
    array (
      'key' => 'core:menu:read',
      'parent' => 'Menu',
      'name' => '读取',
      'code' => '',
      'slug' => 'core:menu:read',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    47 =>
    array (
      'key' => 'core:menu:save',
      'parent' => 'Menu',
      'name' => '添加',
      'code' => '',
      'slug' => 'core:menu:save',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    48 =>
    array (
      'key' => 'core:menu:update',
      'parent' => 'Menu',
      'name' => '修改',
      'code' => '',
      'slug' => 'core:menu:update',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    49 =>
    array (
      'key' => 'core:menu:destroy',
      'parent' => 'Menu',
      'name' => '删除',
      'code' => '',
      'slug' => 'core:menu:destroy',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    50 =>
    array (
      'key' => 'core:config:index',
      'parent' => 'Config',
      'name' => '数据列表',
      'code' => '',
      'slug' => 'core:config:index',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    51 =>
    array (
      'key' => 'core:config:edit',
      'parent' => 'Config',
      'name' => '管理',
      'code' => '',
      'slug' => 'core:config:edit',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    52 =>
    array (
      'key' => 'core:config:update',
      'parent' => 'Config',
      'name' => '修改',
      'code' => '',
      'slug' => 'core:config:update',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    53 =>
    array (
      'key' => 'core:dict:index',
      'parent' => 'Dict',
      'name' => '数据列表',
      'code' => '',
      'slug' => 'core:dict:index',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    54 =>
    array (
      'key' => 'core:dict:edit',
      'parent' => 'Dict',
      'name' => '管理',
      'code' => '',
      'slug' => 'core:dict:edit',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    55 =>
    array (
      'key' => 'core:attachment:index',
      'parent' => 'Attachment',
      'name' => '数据列表',
      'code' => '',
      'slug' => 'core:attachment:index',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    56 =>
    array (
      'key' => 'core:attachment:edit',
      'parent' => 'Attachment',
      'name' => '管理',
      'code' => '',
      'slug' => 'core:attachment:edit',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    57 =>
    array (
      'key' => 'core:database:index',
      'parent' => 'Database',
      'name' => '数据表列表',
      'code' => '',
      'slug' => 'core:database:index',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    58 =>
    array (
      'key' => 'core:database:edit',
      'parent' => 'Database',
      'name' => '数据表维护',
      'code' => '',
      'slug' => 'core:database:edit',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    59 =>
    array (
      'key' => 'core:recycle:index',
      'parent' => 'Database',
      'name' => '回收站数据',
      'code' => '',
      'slug' => 'core:recycle:index',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    60 =>
    array (
      'key' => 'core:recycle:edit',
      'parent' => 'Database',
      'name' => '回收站管理',
      'code' => '',
      'slug' => 'core:recycle:edit',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    61 =>
    array (
      'key' => 'core:logs:login',
      'parent' => 'LoginLog',
      'name' => '数据列表',
      'code' => '',
      'slug' => 'core:logs:login',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    62 =>
    array (
      'key' => 'core:logs:deleteLogin',
      'parent' => 'LoginLog',
      'name' => '删除',
      'code' => '',
      'slug' => 'core:logs:deleteLogin',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    63 =>
    array (
      'key' => 'core:logs:Oper',
      'parent' => 'OperLog',
      'name' => '数据列表',
      'code' => '',
      'slug' => 'core:logs:Oper',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    64 =>
    array (
      'key' => 'core:logs:deleteOper',
      'parent' => 'OperLog',
      'name' => '删除',
      'code' => '',
      'slug' => 'core:logs:deleteOper',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    65 =>
    array (
      'key' => 'core:email:index',
      'parent' => 'EmailLog',
      'name' => '数据列表',
      'code' => '',
      'slug' => 'core:email:index',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    66 =>
    array (
      'key' => 'core:email:destroy',
      'parent' => 'EmailLog',
      'name' => '删除',
      'code' => '',
      'slug' => 'core:email:destroy',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    67 =>
    array (
      'key' => 'Server',
      'parent' => 'Safeguard',
      'name' => '服务监控',
      'code' => 'Server',
      'slug' => '',
      'type' => 2,
      'path' => 'server',
      'component' => '/safeguard/server',
      'icon' => 'ri:server-line',
      'sort' => 90,
      'link_url' => '',
    ),
    68 =>
    array (
      'key' => 'core:server:monitor',
      'parent' => 'Server',
      'name' => '数据列表',
      'code' => '',
      'slug' => 'core:server:monitor',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    69 =>
    array (
      'key' => 'core:server:cache',
      'parent' => 'Cache',
      'name' => '数据列表',
      'code' => '',
      'slug' => 'core:server:cache',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    70 =>
    array (
      'key' => 'core:server:clear',
      'parent' => 'Cache',
      'name' => '缓存清理',
      'code' => '',
      'slug' => 'core:server:clear',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    71 =>
    array (
      'key' => 'core:console:list',
      'parent' => 'Console',
      'name' => '登录数据统计',
      'code' => '',
      'slug' => 'core:console:list',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    72 =>
    array (
      'key' => 'Permission',
      'parent' => NULL,
      'name' => '附加权限',
      'code' => 'Permission',
      'slug' => '',
      'path' => 'permission',
      'component' => '',
      'icon' => 'ri:apps-2-ai-line',
      'link_url' => '',
      'is_hidden' => 1,
    ),
    73 =>
    array (
      'key' => 'core:system:uploadImage',
      'parent' => 'Permission',
      'name' => '上传图片',
      'code' => '',
      'slug' => 'core:system:uploadImage',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    74 =>
    array (
      'key' => 'core:system:uploadFile',
      'parent' => 'Permission',
      'name' => '上传文件',
      'code' => '',
      'slug' => 'core:system:uploadFile',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    75 =>
    array (
      'key' => 'core:system:resource',
      'parent' => 'Permission',
      'name' => '附件列表',
      'code' => '',
      'slug' => 'core:system:resource',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    76 =>
    array (
      'key' => 'core:system:user',
      'parent' => 'Permission',
      'name' => '用户列表',
      'code' => '',
      'slug' => 'core:system:user',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    77 =>
    array (
      'key' => 'Tool',
      'parent' => NULL,
      'name' => '工具',
      'code' => 'Tool',
      'slug' => '',
      'path' => '/tool',
      'component' => '',
      'icon' => 'ri:tools-line',
      'link_url' => '',
    ),
    78 =>
    array (
      'key' => 'Code',
      'parent' => 'Tool',
      'name' => '代码生成',
      'code' => 'Code',
      'slug' => '',
      'type' => 2,
      'path' => 'code',
      'component' => '/tool/code',
      'icon' => 'ri:code-s-slash-line',
      'link_url' => '',
    ),
    79 =>
    array (
      'key' => 'Crontab',
      'parent' => 'Tool',
      'name' => '定时任务',
      'code' => 'Crontab',
      'slug' => '',
      'type' => 2,
      'path' => 'crontab',
      'component' => '/tool/crontab',
      'icon' => 'ri:time-line',
      'link_url' => '',
    ),
    80 =>
    array (
      'key' => 'tool:crontab:index',
      'parent' => 'Crontab',
      'name' => '数据列表',
      'code' => '',
      'slug' => 'tool:crontab:index',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    81 =>
    array (
      'key' => 'tool:crontab:edit',
      'parent' => 'Crontab',
      'name' => '管理',
      'code' => '',
      'slug' => 'tool:crontab:edit',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    82 =>
    array (
      'key' => 'tool:crontab:run',
      'parent' => 'Crontab',
      'name' => '运行任务',
      'code' => '',
      'slug' => 'tool:crontab:run',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    83 =>
    array (
      'key' => 'tool:code:index',
      'parent' => 'Code',
      'name' => '数据列表',
      'code' => '',
      'slug' => 'tool:code:index',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    84 =>
    array (
      'key' => 'tool:code:edit',
      'parent' => 'Code',
      'name' => '管理',
      'code' => '',
      'slug' => 'tool:code:edit',
      'type' => 3,
      'path' => '',
      'component' => '',
      'icon' => '',
      'link_url' => '',
    ),
    85 =>
    array (
      'key' => 'Plugin',
      'parent' => NULL,
      'name' => '插件市场',
      'code' => 'Plugin',
      'slug' => '',
      'type' => 2,
      'path' => '/plugin',
      'component' => '/plugin/saipackage/install/index',
      'icon' => 'ri:apps-2-ai-line',
      'link_url' => '',
      'status' => 2,
      'remark' => '',
    ),
    86 =>
    array (
      'key' => 'MgGame',
      'parent' => NULL,
      'name' => '游戏平台',
      'code' => 'MgGame',
      'path' => '/game',
      'component' => '',
      'icon' => 'ri:gamepad-line',
      'sort' => 20,
    ),
    87 =>
    array (
      'key' => 'MgDashboard',
      'parent' => 'MgGame',
      'name' => '运营看板',
      'code' => 'MgDashboard',
      'slug' => '',
      'type' => 2,
      'path' => 'dashboard',
      'component' => '/game/dashboard',
      'icon' => 'ri:dashboard-line',
      'link_url' => '',
      'remark' => '',
    ),
    88 =>
    array (
      'key' => 'MgEnterprise',
      'parent' => 'MgGame',
      'name' => '企业列表',
      'code' => 'MgEnterprise',
      'type' => 2,
      'path' => 'enterprise',
      'component' => '/game/enterprise',
      'icon' => 'ri:building-line',
      'sort' => 90,
    ),
    89 =>
    array (
      'key' => 'MgMerchant',
      'parent' => 'MgGame',
      'name' => '商户列表',
      'code' => 'MgMerchant',
      'type' => 2,
      'path' => 'merchant',
      'component' => '/game/merchant',
      'icon' => 'ri:key-2-line',
      'sort' => 80,
    ),
    90 =>
    array (
      'key' => 'MgList',
      'parent' => 'MgGame',
      'name' => '游戏列表',
      'code' => 'MgList',
      'type' => 2,
      'path' => 'list',
      'component' => '/game/list',
      'icon' => 'ri:apps-line',
      'sort' => 70,
    ),
    91 =>
    array (
      'key' => 'MgUsers',
      'parent' => 'MgGame',
      'name' => '玩家列表',
      'code' => 'MgUsers',
      'type' => 2,
      'path' => 'users',
      'component' => '/game/users',
      'icon' => 'ri:user-smile-line',
      'sort' => 60,
    ),
    92 =>
    array (
      'key' => 'MgBets',
      'parent' => 'MgGame',
      'name' => '注单记录',
      'code' => 'MgBets',
      'type' => 2,
      'path' => 'bets',
      'component' => '/game/bets',
      'icon' => 'ri:file-list-3-line',
      'sort' => 50,
    ),
    93 =>
    array (
      'key' => 'MgBills',
      'parent' => 'MgGame',
      'name' => '流水记录',
      'code' => 'MgBills',
      'type' => 2,
      'path' => 'bills',
      'component' => '/game/bills',
      'icon' => 'ri:exchange-funds-line',
      'sort' => 40,
    ),
    94 =>
    array (
      'key' => 'MgReports',
      'parent' => 'MgGame',
      'name' => '游戏日报',
      'code' => 'MgReports',
      'type' => 2,
      'path' => 'reports',
      'component' => '/game/reports',
      'icon' => 'ri:bar-chart-box-line',
      'sort' => 30,
    ),
    95 =>
    array (
      'key' => 'app:game:dashboard:index',
      'parent' => 'MgDashboard',
      'name' => '查看看板',
      'slug' => 'app:game:dashboard:index',
      'type' => 3,
    ),
    96 =>
    array (
      'key' => 'app:game:enterprise:index',
      'parent' => 'MgEnterprise',
      'name' => '企业列表',
      'slug' => 'app:game:enterprise:index',
      'type' => 3,
    ),
    97 =>
    array (
      'key' => 'app:game:enterprise:save',
      'parent' => 'MgEnterprise',
      'name' => '创建企业',
      'slug' => 'app:game:enterprise:save',
      'type' => 3,
    ),
    98 =>
    array (
      'key' => 'app:game:enterprise:update',
      'parent' => 'MgEnterprise',
      'name' => '修改企业',
      'slug' => 'app:game:enterprise:update',
      'type' => 3,
    ),
    99 =>
    array (
      'key' => 'app:game:enterprise:user:index',
      'parent' => 'MgEnterprise',
      'name' => '账号列表',
      'slug' => 'app:game:enterprise:user:index',
      'type' => 3,
    ),
    100 =>
    array (
      'key' => 'app:game:enterprise:user:save',
      'parent' => 'MgEnterprise',
      'name' => '创建子账号',
      'slug' => 'app:game:enterprise:user:save',
      'type' => 3,
    ),
    101 =>
    array (
      'key' => 'app:game:enterprise:user:update',
      'parent' => 'MgEnterprise',
      'name' => '启停子账号',
      'slug' => 'app:game:enterprise:user:update',
      'type' => 3,
    ),
    102 =>
    array (
      'key' => 'app:game:merchant:index',
      'parent' => 'MgMerchant',
      'name' => '商户列表',
      'slug' => 'app:game:merchant:index',
      'type' => 3,
    ),
    103 =>
    array (
      'key' => 'app:game:merchant:save',
      'parent' => 'MgMerchant',
      'name' => '创建商户',
      'slug' => 'app:game:merchant:save',
      'type' => 3,
    ),
    104 =>
    array (
      'key' => 'app:game:merchant:update',
      'parent' => 'MgMerchant',
      'name' => '修改商户',
      'slug' => 'app:game:merchant:update',
      'type' => 3,
    ),
    105 =>
    array (
      'key' => 'app:game:merchant:secret',
      'parent' => 'MgMerchant',
      'name' => '查看密钥',
      'slug' => 'app:game:merchant:secret',
      'type' => 3,
    ),
    106 =>
    array (
      'key' => 'app:game:merchant:grant',
      'parent' => 'MgMerchant',
      'name' => '游戏授权',
      'slug' => 'app:game:merchant:grant',
      'type' => 3,
    ),
    107 =>
    array (
      'key' => 'app:game:merchant:credit',
      'parent' => 'MgMerchant',
      'name' => '额度管理',
      'slug' => 'app:game:merchant:credit',
      'type' => 3,
    ),
    108 =>
    array (
      'key' => 'app:game:list:index',
      'parent' => 'MgList',
      'name' => '查看游戏列表',
      'slug' => 'app:game:list:index',
      'type' => 3,
    ),
    109 =>
    array (
      'key' => 'app:game:list:sync',
      'parent' => 'MgList',
      'name' => '同步游戏列表',
      'slug' => 'app:game:list:sync',
      'type' => 3,
    ),
    110 =>
    array (
      'key' => 'app:game:list:update',
      'parent' => 'MgList',
      'name' => '启停游戏',
      'slug' => 'app:game:list:update',
      'type' => 3,
    ),
    111 =>
    array (
      'key' => 'app:game:user:index',
      'parent' => 'MgUsers',
      'name' => '玩家列表',
      'slug' => 'app:game:user:index',
      'type' => 3,
    ),
    112 =>
    array (
      'key' => 'app:game:bet:index',
      'parent' => 'MgBets',
      'name' => '注单列表',
      'slug' => 'app:game:bet:index',
      'type' => 3,
    ),
    113 =>
    array (
      'key' => 'app:game:bill:index',
      'parent' => 'MgBills',
      'name' => '玩家流水',
      'slug' => 'app:game:bill:index',
      'type' => 3,
    ),
    114 =>
    array (
      'key' => 'app:game:merchant-bill:index',
      'parent' => 'MgBills',
      'name' => '商户流水',
      'slug' => 'app:game:merchant-bill:index',
      'type' => 3,
    ),
    115 =>
    array (
      'key' => 'app:game:report:index',
      'parent' => 'MgReports',
      'name' => '游戏日报',
      'slug' => 'app:game:report:index',
      'type' => 3,
    ),
    116 =>
    array (
      'key' => 'app:game:document:index',
      'parent' => 'Document',
      'name' => '查看对接文档',
      'slug' => 'app:game:document:index',
      'type' => 3,
    ),
    117 =>
    array (
      'key' => 'MgExchangeRates',
      'parent' => 'MgGame',
      'name' => '汇率快照',
      'code' => 'MgExchangeRates',
      'type' => 2,
      'path' => 'exchange-rates',
      'component' => '/game/exchange-rates',
      'icon' => 'ri:exchange-dollar-line',
      'sort' => 20,
      'remark' => 'game_super_admin',
    ),
    118 =>
    array (
      'key' => 'MgSettings',
      'parent' => 'MgGame',
      'name' => '全局设置',
      'code' => 'MgSettings',
      'type' => 2,
      'path' => 'settings',
      'component' => '/game/settings',
      'icon' => 'ri:settings-3-line',
      'sort' => 10,
      'remark' => 'game_super_admin',
    ),
    119 =>
    array (
      'key' => 'app:game:exchange-rate:index',
      'parent' => 'MgExchangeRates',
      'name' => '查看汇率快照',
      'slug' => 'app:game:exchange-rate:index',
      'type' => 3,
    ),
    120 =>
    array (
      'key' => 'app:game:exchange-rate:update',
      'parent' => 'MgExchangeRates',
      'name' => '更新今日汇率',
      'slug' => 'app:game:exchange-rate:update',
      'type' => 3,
    ),
    121 =>
    array (
      'key' => 'app:game:settings:index',
      'parent' => 'MgSettings',
      'name' => '查看全局设置',
      'slug' => 'app:game:settings:index',
      'type' => 3,
    ),
    122 =>
    array (
      'key' => 'app:game:settings:update',
      'parent' => 'MgSettings',
      'name' => '修改全局设置',
      'slug' => 'app:game:settings:update',
      'type' => 3,
    ),
    123 =>
    array (
      'key' => 'MgPlatformAdmin',
      'parent' => 'MgGame',
      'name' => '平台管理',
      'code' => 'MgPlatformAdmin',
      'type' => 2,
      'path' => 'platform-admin',
      'component' => '/game/platform-admin',
      'icon' => 'ri:admin-line',
      'sort' => 85,
      'remark' => 'game_super_admin',
    ),
    124 =>
    array (
      'key' => 'app:game:platform-admin:index',
      'parent' => 'MgPlatformAdmin',
      'name' => '平台账号列表',
      'slug' => 'app:game:platform-admin:index',
      'type' => 3,
    ),
    125 =>
    array (
      'key' => 'app:game:platform-admin:save',
      'parent' => 'MgPlatformAdmin',
      'name' => '创建平台账号',
      'slug' => 'app:game:platform-admin:save',
      'type' => 3,
    ),
    126 =>
    array (
      'key' => 'app:game:platform-admin:update',
      'parent' => 'MgPlatformAdmin',
      'name' => '修改平台账号',
      'slug' => 'app:game:platform-admin:update',
      'type' => 3,
    ),
    127 =>
    array (
      'key' => 'app:game:platform-admin:delete',
      'parent' => 'MgPlatformAdmin',
      'name' => '删除平台账号',
      'slug' => 'app:game:platform-admin:delete',
      'type' => 3,
    ),
    128 =>
    array (
      'key' => 'app:game:list:trial',
      'parent' => 'MgList',
      'name' => '试玩游戏',
      'slug' => 'app:game:list:trial',
      'type' => 3,
    ),
  ),
  'roles' =>
  array (
    'super_admin' =>
    array (
      'name' => '超级管理员',
      'level' => 100,
      'data_scope' => 1,
      'remark' => '系统维护者，拥有所有权限',
      'sort' => 100,
      'status' => 1,
      'menus' => '*',
    ),
    'enterprise_owner' =>
    array (
      'name' => '企业负责人',
      'level' => 10,
      'data_scope' => 4,
      'remark' => '管理本企业商户参数和子账号',
      'sort' => 20,
      'status' => 1,
      'menus' =>
      array (
        0 => 'Document',
        1 => 'MgGame',
        2 => 'MgDashboard',
        3 => 'MgEnterprise',
        4 => 'MgMerchant',
        5 => 'MgList',
        6 => 'MgUsers',
        7 => 'MgBets',
        8 => 'MgBills',
        9 => 'MgReports',
        10 => 'app:game:dashboard:index',
        11 => 'app:game:enterprise:index',
        12 => 'app:game:enterprise:user:index',
        13 => 'app:game:enterprise:user:save',
        14 => 'app:game:enterprise:user:update',
        15 => 'app:game:merchant:index',
        16 => 'app:game:merchant:update',
        17 => 'app:game:merchant:secret',
        18 => 'app:game:merchant:grant',
        19 => 'app:game:list:index',
        20 => 'app:game:user:index',
        21 => 'app:game:bet:index',
        22 => 'app:game:bill:index',
        23 => 'app:game:merchant-bill:index',
        24 => 'app:game:report:index',
        25 => 'app:game:document:index',
      ),
    ),
    'enterprise_staff' =>
    array (
      'name' => '企业子账号',
      'level' => 5,
      'data_scope' => 4,
      'remark' => '只查看本企业游戏和账务数据',
      'sort' => 30,
      'status' => 1,
      'menus' =>
      array (
        0 => 'Document',
        1 => 'MgGame',
        2 => 'MgDashboard',
        3 => 'MgMerchant',
        4 => 'MgList',
        5 => 'MgUsers',
        6 => 'MgBets',
        7 => 'MgBills',
        8 => 'MgReports',
        9 => 'app:game:dashboard:index',
        10 => 'app:game:merchant:index',
        11 => 'app:game:merchant:secret',
        12 => 'app:game:list:index',
        13 => 'app:game:user:index',
        14 => 'app:game:bet:index',
        15 => 'app:game:bill:index',
        16 => 'app:game:merchant-bill:index',
        17 => 'app:game:report:index',
        18 => 'app:game:document:index',
      ),
    ),
    'game_super_admin' =>
    array (
      'name' => '游戏超管',
      'level' => 100,
      'data_scope' => 1,
      'remark' => '仅管理游戏平台并查看全部企业和商户数据',
      'sort' => 10,
      'status' => 1,
      'menus' =>
      array (
        0 => 'Document',
        1 => 'MgGame',
        2 => 'MgDashboard',
        3 => 'MgEnterprise',
        4 => 'MgMerchant',
        5 => 'MgList',
        6 => 'MgUsers',
        7 => 'MgBets',
        8 => 'MgBills',
        9 => 'MgReports',
        10 => 'app:game:dashboard:index',
        11 => 'app:game:enterprise:index',
        12 => 'app:game:enterprise:save',
        13 => 'app:game:enterprise:update',
        14 => 'app:game:enterprise:user:index',
        15 => 'app:game:enterprise:user:save',
        16 => 'app:game:enterprise:user:update',
        17 => 'app:game:merchant:index',
        18 => 'app:game:merchant:save',
        19 => 'app:game:merchant:update',
        20 => 'app:game:merchant:secret',
        21 => 'app:game:merchant:grant',
        22 => 'app:game:merchant:credit',
        23 => 'app:game:list:index',
        24 => 'app:game:list:sync',
        25 => 'app:game:list:update',
        26 => 'app:game:list:trial',
        27 => 'app:game:user:index',
        28 => 'app:game:bet:index',
        29 => 'app:game:bill:index',
        30 => 'app:game:merchant-bill:index',
        31 => 'app:game:report:index',
        32 => 'app:game:document:index',
        33 => 'MgExchangeRates',
        34 => 'MgSettings',
        35 => 'app:game:exchange-rate:index',
        36 => 'app:game:exchange-rate:update',
        37 => 'app:game:settings:index',
        38 => 'app:game:settings:update',
        39 => 'MgPlatformAdmin',
        40 => 'app:game:platform-admin:index',
        41 => 'app:game:platform-admin:save',
        42 => 'app:game:platform-admin:update',
        43 => 'app:game:platform-admin:delete',
      ),
    ),
  ),
  'config_groups' =>
  array (
    'site_config' =>
    array (
      'name' => '站点配置',
      'remark' => '',
    ),
    'upload_config' =>
    array (
      'name' => '上传配置',
      'remark' => NULL,
    ),
    'email_config' =>
    array (
      'name' => '邮件服务',
      'remark' => NULL,
    ),
  ),
  'configs' =>
  array (
    0 =>
    array (
      'group' => 'site_config',
      'key' => 'site_copyright',
      'value' => 'Copyright © 2026 MGames',
      'name' => '版权信息',
      'input_type' => 'textarea',
      'config_select_data' => NULL,
      'sort' => 96,
      'remark' => '',
    ),
    1 =>
    array (
      'group' => 'site_config',
      'key' => 'site_desc',
      'value' => 'MGames-游戏平台',
      'name' => '网站描述',
      'input_type' => 'textarea',
      'config_select_data' => NULL,
      'sort' => 97,
      'remark' => NULL,
    ),
    2 =>
    array (
      'group' => 'site_config',
      'key' => 'site_keywords',
      'value' => 'MGames-游戏平台',
      'name' => '网站关键字',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 98,
      'remark' => NULL,
    ),
    3 =>
    array (
      'group' => 'site_config',
      'key' => 'site_name',
      'value' => 'MGames-游戏平台',
      'name' => '网站名称',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 99,
      'remark' => NULL,
    ),
    4 =>
    array (
      'group' => 'site_config',
      'key' => 'site_record_number',
      'value' => '',
      'name' => '网站备案号',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 95,
      'remark' => NULL,
    ),
    5 =>
    array (
      'group' => 'upload_config',
      'key' => 'upload_allow_file',
      'value' => 'txt,doc,docx,xls,xlsx,ppt,pptx,rar,zip,7z,gz,pdf,wps,md,jpg,png,jpeg,mp4,pem,crt',
      'name' => '文件类型',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => NULL,
    ),
    6 =>
    array (
      'group' => 'upload_config',
      'key' => 'upload_allow_image',
      'value' => 'jpg,jpeg,png,gif,svg,bmp',
      'name' => '图片类型',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => NULL,
    ),
    7 =>
    array (
      'group' => 'upload_config',
      'key' => 'upload_mode',
      'value' => '1',
      'name' => '上传模式',
      'input_type' => 'select',
      'config_select_data' => '[{"label":"本地上传","value":"1"},{"label":"阿里云OSS","value":"2"},{"label":"七牛云","value":"3"},{"label":"腾讯云COS","value":"4"},{"label":"亚马逊S3","value":"5"}]',
      'sort' => 99,
      'remark' => NULL,
    ),
    8 =>
    array (
      'group' => 'upload_config',
      'key' => 'upload_size',
      'value' => '52428800',
      'name' => '上传大小',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 88,
      'remark' => '单位Byte,1MB=1024*1024Byte',
    ),
    9 =>
    array (
      'group' => 'upload_config',
      'key' => 'local_root',
      'value' => 'public/storage/',
      'name' => '本地存储路径',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '本地存储文件路径',
    ),
    10 =>
    array (
      'group' => 'upload_config',
      'key' => 'local_domain',
      'value' => '',
      'name' => '本地存储域名',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => 'http://127.0.0.1:8787',
    ),
    11 =>
    array (
      'group' => 'upload_config',
      'key' => 'local_uri',
      'value' => '/storage/',
      'name' => '本地访问路径',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '访问是通过domain + uri',
    ),
    12 =>
    array (
      'group' => 'upload_config',
      'key' => 'qiniu_accessKey',
      'value' => '',
      'name' => '七牛key',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '七牛云存储secretId',
    ),
    13 =>
    array (
      'group' => 'upload_config',
      'key' => 'qiniu_secretKey',
      'value' => '',
      'name' => '七牛secret',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '七牛云存储secretKey',
    ),
    14 =>
    array (
      'group' => 'upload_config',
      'key' => 'qiniu_bucket',
      'value' => '',
      'name' => '七牛bucket',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '七牛云存储bucket',
    ),
    15 =>
    array (
      'group' => 'upload_config',
      'key' => 'qiniu_dirname',
      'value' => '',
      'name' => '七牛dirname',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '七牛云存储dirname',
    ),
    16 =>
    array (
      'group' => 'upload_config',
      'key' => 'qiniu_domain',
      'value' => '',
      'name' => '七牛domain',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '七牛云存储domain',
    ),
    17 =>
    array (
      'group' => 'upload_config',
      'key' => 'cos_secretId',
      'value' => '',
      'name' => '腾讯Id',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '腾讯云存储secretId',
    ),
    18 =>
    array (
      'group' => 'upload_config',
      'key' => 'cos_secretKey',
      'value' => '',
      'name' => '腾讯key',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '腾讯云secretKey',
    ),
    19 =>
    array (
      'group' => 'upload_config',
      'key' => 'cos_bucket',
      'value' => '',
      'name' => '腾讯bucket',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '腾讯云存储bucket',
    ),
    20 =>
    array (
      'group' => 'upload_config',
      'key' => 'cos_dirname',
      'value' => '',
      'name' => '腾讯dirname',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '腾讯云存储dirname',
    ),
    21 =>
    array (
      'group' => 'upload_config',
      'key' => 'cos_domain',
      'value' => '',
      'name' => '腾讯domain',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '腾讯云存储domain',
    ),
    22 =>
    array (
      'group' => 'upload_config',
      'key' => 'cos_region',
      'value' => '',
      'name' => '腾讯region',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '腾讯云存储region',
    ),
    23 =>
    array (
      'group' => 'upload_config',
      'key' => 'oss_accessKeyId',
      'value' => '',
      'name' => '阿里Id',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '阿里云存储accessKeyId',
    ),
    24 =>
    array (
      'group' => 'upload_config',
      'key' => 'oss_accessKeySecret',
      'value' => '',
      'name' => '阿里Secret',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '阿里云存储accessKeySecret',
    ),
    25 =>
    array (
      'group' => 'upload_config',
      'key' => 'oss_bucket',
      'value' => '',
      'name' => '阿里bucket',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '阿里云存储bucket',
    ),
    26 =>
    array (
      'group' => 'upload_config',
      'key' => 'oss_dirname',
      'value' => '',
      'name' => '阿里dirname',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '阿里云存储dirname',
    ),
    27 =>
    array (
      'group' => 'upload_config',
      'key' => 'oss_domain',
      'value' => '',
      'name' => '阿里domain',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '阿里云存储domain',
    ),
    28 =>
    array (
      'group' => 'upload_config',
      'key' => 'oss_endpoint',
      'value' => '',
      'name' => '阿里endpoint',
      'input_type' => 'input',
      'config_select_data' => NULL,
      'sort' => 0,
      'remark' => '阿里云存储endpoint',
    ),
    29 =>
    array (
      'group' => 'email_config',
      'key' => 'Host',
      'value' => 'smtp.qq.com',
      'name' => 'SMTP服务器',
      'input_type' => 'input',
      'config_select_data' => '',
      'sort' => 100,
      'remark' => '',
    ),
    30 =>
    array (
      'group' => 'email_config',
      'key' => 'Port',
      'value' => '465',
      'name' => 'SMTP端口',
      'input_type' => 'input',
      'config_select_data' => '',
      'sort' => 100,
      'remark' => '',
    ),
    31 =>
    array (
      'group' => 'email_config',
      'key' => 'Username',
      'value' => '',
      'name' => 'SMTP用户名',
      'input_type' => 'input',
      'config_select_data' => '',
      'sort' => 100,
      'remark' => '',
    ),
    32 =>
    array (
      'group' => 'email_config',
      'key' => 'Password',
      'value' => '',
      'name' => 'SMTP密码',
      'input_type' => 'input',
      'config_select_data' => '',
      'sort' => 100,
      'remark' => '',
    ),
    33 =>
    array (
      'group' => 'email_config',
      'key' => 'SMTPSecure',
      'value' => 'ssl',
      'name' => 'SMTP验证方式',
      'input_type' => 'radio',
      'config_select_data' => '[
    {"label":"ssl","value":"ssl"},
    {"label":"tsl","value":"tsl"}
]',
      'sort' => 100,
      'remark' => '',
    ),
    34 =>
    array (
      'group' => 'email_config',
      'key' => 'From',
      'value' => '',
      'name' => '默认发件人',
      'input_type' => 'input',
      'config_select_data' => '',
      'sort' => 100,
      'remark' => '默认发件的邮箱地址',
    ),
    35 =>
    array (
      'group' => 'email_config',
      'key' => 'FromName',
      'value' => '账户注册',
      'name' => '默认发件名称',
      'input_type' => 'input',
      'config_select_data' => '',
      'sort' => 100,
      'remark' => '',
    ),
    36 =>
    array (
      'group' => 'email_config',
      'key' => 'CharSet',
      'value' => 'UTF-8',
      'name' => '编码',
      'input_type' => 'input',
      'config_select_data' => '',
      'sort' => 100,
      'remark' => '',
    ),
    37 =>
    array (
      'group' => 'email_config',
      'key' => 'SMTPDebug',
      'value' => '0',
      'name' => '调试模式',
      'input_type' => 'radio',
      'config_select_data' => '[
    {"label":"关闭","value":"0"},
    {"label":"client","value":"1"},
    {"label":"server","value":"2"}
]',
      'sort' => 100,
      'remark' => '',
    ),
    38 =>
    array (
      'group' => 'upload_config',
      'key' => 's3_key',
      'value' => '',
      'name' => 'key',
      'input_type' => 'input',
      'config_select_data' => '',
      'sort' => 0,
      'remark' => '',
    ),
    39 =>
    array (
      'group' => 'upload_config',
      'key' => 's3_secret',
      'value' => '',
      'name' => 'secret',
      'input_type' => 'input',
      'config_select_data' => '',
      'sort' => 0,
      'remark' => '',
    ),
    40 =>
    array (
      'group' => 'upload_config',
      'key' => 's3_bucket',
      'value' => '',
      'name' => 'bucket',
      'input_type' => 'input',
      'config_select_data' => '',
      'sort' => 0,
      'remark' => '',
    ),
    41 =>
    array (
      'group' => 'upload_config',
      'key' => 's3_dirname',
      'value' => '',
      'name' => 'dirname',
      'input_type' => 'input',
      'config_select_data' => '',
      'sort' => 0,
      'remark' => '',
    ),
    42 =>
    array (
      'group' => 'upload_config',
      'key' => 's3_domain',
      'value' => '',
      'name' => 'domain',
      'input_type' => 'input',
      'config_select_data' => '',
      'sort' => 0,
      'remark' => '',
    ),
    43 =>
    array (
      'group' => 'upload_config',
      'key' => 's3_region',
      'value' => '',
      'name' => 'region',
      'input_type' => 'input',
      'config_select_data' => '',
      'sort' => 0,
      'remark' => '',
    ),
    44 =>
    array (
      'group' => 'upload_config',
      'key' => 's3_version',
      'value' => '',
      'name' => 'version',
      'input_type' => 'input',
      'config_select_data' => '',
      'sort' => 0,
      'remark' => '',
    ),
    45 =>
    array (
      'group' => 'upload_config',
      'key' => 's3_use_path_style_endpoint',
      'value' => '',
      'name' => 'path_style_endpoint',
      'input_type' => 'input',
      'config_select_data' => '',
      'sort' => 0,
      'remark' => '',
    ),
    46 =>
    array (
      'group' => 'upload_config',
      'key' => 's3_endpoint',
      'value' => '',
      'name' => 'endpoint',
      'input_type' => 'input',
      'config_select_data' => '',
      'sort' => 0,
      'remark' => '',
    ),
    47 =>
    array (
      'group' => 'upload_config',
      'key' => 's3_acl',
      'value' => '',
      'name' => 'acl',
      'input_type' => 'input',
      'config_select_data' => '',
      'sort' => 0,
      'remark' => '',
    ),
  ),
  'dict_types' =>
  array (
    'upload_mode' =>
    array (
      'name' => '存储模式',
      'status' => 1,
      'remark' => '上传文件存储模式',
      'data' =>
      array (
        0 =>
        array (
          'label' => '亚马逊S3',
          'value' => '5',
          'color' => '#ff80c8',
          'code' => 'upload_mode',
          'sort' => 95,
          'status' => 1,
          'remark' => '',
        ),
        1 =>
        array (
          'label' => '腾讯云COS',
          'value' => '4',
          'color' => '#1d84ff',
          'code' => 'upload_mode',
          'sort' => 96,
          'status' => 1,
          'remark' => '',
        ),
        2 =>
        array (
          'label' => '七牛云',
          'value' => '3',
          'color' => '#00ced1',
          'code' => 'upload_mode',
          'sort' => 97,
          'status' => 1,
          'remark' => '',
        ),
        3 =>
        array (
          'label' => '阿里云OSS',
          'value' => '2',
          'color' => '#f9901f',
          'code' => 'upload_mode',
          'sort' => 98,
          'status' => 1,
          'remark' => '',
        ),
        4 =>
        array (
          'label' => '本地存储',
          'value' => '1',
          'color' => '#5d87ff',
          'code' => 'upload_mode',
          'sort' => 99,
          'status' => 1,
          'remark' => '',
        ),
      ),
    ),
    'data_status' =>
    array (
      'name' => '数据状态',
      'status' => 1,
      'remark' => '通用数据状态',
      'data' =>
      array (
        0 =>
        array (
          'label' => '正常',
          'value' => '1',
          'color' => '#13deb9',
          'code' => 'data_status',
          'sort' => 0,
          'status' => 1,
          'remark' => '1为正常',
        ),
        1 =>
        array (
          'label' => '停用',
          'value' => '2',
          'color' => '#ff4d4f',
          'code' => 'data_status',
          'sort' => 0,
          'status' => 1,
          'remark' => '2为停用',
        ),
      ),
    ),
    'dashboard' =>
    array (
      'name' => '后台首页',
      'status' => 1,
      'remark' => NULL,
      'data' =>
      array (
        0 =>
        array (
          'label' => '工作台',
          'value' => 'work',
          'color' => '#ff8c00',
          'code' => 'dashboard',
          'sort' => 50,
          'status' => 1,
          'remark' => '员工使用',
        ),
        1 =>
        array (
          'label' => '统计页面',
          'value' => 'statistics',
          'color' => '#00ced1',
          'code' => 'dashboard',
          'sort' => 100,
          'status' => 1,
          'remark' => '管理员用',
        ),
      ),
    ),
    'gender' =>
    array (
      'name' => '性别',
      'status' => 1,
      'remark' => '',
      'data' =>
      array (
        0 =>
        array (
          'label' => '男',
          'value' => '1',
          'color' => '#5d87ff',
          'code' => 'gender',
          'sort' => 0,
          'status' => 1,
          'remark' => '',
        ),
        1 =>
        array (
          'label' => '女',
          'value' => '2',
          'color' => '#ff4500',
          'code' => 'gender',
          'sort' => 0,
          'status' => 1,
          'remark' => '',
        ),
        2 =>
        array (
          'label' => '未知',
          'value' => '3',
          'color' => '#b48df3',
          'code' => 'gender',
          'sort' => 0,
          'status' => 1,
          'remark' => '',
        ),
      ),
    ),
    'attachment_type' =>
    array (
      'name' => '附件类型',
      'status' => 1,
      'remark' => NULL,
      'data' =>
      array (
        0 =>
        array (
          'label' => '应用程序',
          'value' => 'application',
          'color' => '#ff8c00',
          'code' => 'attachment_type',
          'sort' => 6,
          'status' => 1,
          'remark' => '',
        ),
        1 =>
        array (
          'label' => '视频',
          'value' => 'video',
          'color' => '#ff4500',
          'code' => 'attachment_type',
          'sort' => 7,
          'status' => 1,
          'remark' => '',
        ),
        2 =>
        array (
          'label' => '音频',
          'value' => 'audio',
          'color' => '#00ced1',
          'code' => 'attachment_type',
          'sort' => 8,
          'status' => 1,
          'remark' => '',
        ),
        3 =>
        array (
          'label' => '文档',
          'value' => 'text',
          'color' => '#1d84ff',
          'code' => 'attachment_type',
          'sort' => 9,
          'status' => 1,
          'remark' => '',
        ),
        4 =>
        array (
          'label' => '图片',
          'value' => 'image',
          'color' => '#60c041',
          'code' => 'attachment_type',
          'sort' => 10,
          'status' => 1,
          'remark' => '',
        ),
      ),
    ),
    'menu_type' =>
    array (
      'name' => '菜单类型',
      'status' => 1,
      'remark' => '',
      'data' =>
      array (
        0 =>
        array (
          'label' => '目录',
          'value' => '1',
          'color' => '#909399',
          'code' => 'menu_type',
          'sort' => 100,
          'status' => 1,
          'remark' => '',
        ),
        1 =>
        array (
          'label' => '菜单',
          'value' => '2',
          'color' => '#1e90ff',
          'code' => 'menu_type',
          'sort' => 100,
          'status' => 1,
          'remark' => '',
        ),
        2 =>
        array (
          'label' => '按钮',
          'value' => '3',
          'color' => '#ff4500',
          'code' => 'menu_type',
          'sort' => 100,
          'status' => 1,
          'remark' => '',
        ),
        3 =>
        array (
          'label' => '外链',
          'value' => '4',
          'color' => '#00ced1',
          'code' => 'menu_type',
          'sort' => 100,
          'status' => 1,
          'remark' => '',
        ),
      ),
    ),
    'yes_or_no' =>
    array (
      'name' => '是否',
      'status' => 1,
      'remark' => '',
      'data' =>
      array (
        0 =>
        array (
          'label' => '是',
          'value' => '1',
          'color' => '#60c041',
          'code' => 'yes_or_no',
          'sort' => 100,
          'status' => 1,
          'remark' => '',
        ),
        1 =>
        array (
          'label' => '否',
          'value' => '2',
          'color' => '#ff4500',
          'code' => 'yes_or_no',
          'sort' => 100,
          'status' => 1,
          'remark' => '',
        ),
      ),
    ),
    'crontab_task_type' =>
    array (
      'name' => '定时任务类型',
      'status' => 1,
      'remark' => '',
      'data' =>
      array (
        0 =>
        array (
          'label' => 'URL任务GET',
          'value' => '1',
          'color' => '#5d87ff',
          'code' => 'crontab_task_type',
          'sort' => 100,
          'status' => 1,
          'remark' => '',
        ),
        1 =>
        array (
          'label' => 'URL任务POST',
          'value' => '2',
          'color' => '#00ced1',
          'code' => 'crontab_task_type',
          'sort' => 100,
          'status' => 1,
          'remark' => '',
        ),
        2 =>
        array (
          'label' => '类任务',
          'value' => '3',
          'color' => '#ff8c00',
          'code' => 'crontab_task_type',
          'sort' => 100,
          'status' => 1,
          'remark' => '',
        ),
      ),
    ),
  ),
  'categories' =>
  array (
    0 =>
    array (
      'key' => '全部分类',
      'parent' => NULL,
      'sort' => 100,
      'status' => 1,
      'remark' => NULL,
    ),
    1 =>
    array (
      'key' => '图片分类',
      'parent' => '全部分类',
      'sort' => 100,
      'status' => 1,
      'remark' => NULL,
    ),
    2 =>
    array (
      'key' => '文件分类',
      'parent' => '全部分类',
      'sort' => 100,
      'status' => 1,
      'remark' => NULL,
    ),
    3 =>
    array (
      'key' => '系统图片',
      'parent' => '全部分类',
      'sort' => 100,
      'status' => 1,
      'remark' => NULL,
    ),
    4 =>
    array (
      'key' => '其他分类',
      'parent' => '全部分类',
      'sort' => 100,
      'status' => 1,
      'remark' => NULL,
    ),
  ),
  'department' =>
  array (
    'name' => 'MGames',
    'code' => 'MGAMES',
    'sort' => 100,
    'status' => 1,
  ),
  'game_configs' =>
  array (
    0 =>
    array (
      'type' => 'platform',
      'code' => 'platform_timezone',
      'name' => '平台统计时区',
      'value' => 'Asia/Shanghai',
      'remark' => '平台日报和趋势的日期边界；修改后需要重建平台统计',
      'status' => 1,
    ),
    1 =>
    array (
      'type' => 'platform',
      'code' => 'platform_currency_code',
      'name' => '平台统计币种',
      'value' => 'USD',
      'remark' => '平台多币种合计的折算币种；修改后需要重建平台折算金额',
      'status' => 1,
    ),
    2 =>
    array (
      'type' => 'currency',
      'code' => 'exchange_rate_display_codes',
      'name' => '常用汇率币种',
      'value' =>
      array (
        0 => 'USD',
        1 => 'USDT',
        2 => 'CNY',
        3 => 'EUR',
        4 => 'GBP',
        5 => 'INR',
        6 => 'PKR',
        7 => 'BRL',
        8 => 'MXN',
      ),
      'remark' => '汇率快照列表默认展开的币种',
      'status' => 1,
    ),
  ),
  'game_users' =>
  array (
    0 =>
    array (
      'id' => 1,
      'merchant_id' => 0,
      'nickname' => '系统玩家',
      'status' => 1,
    ),
  ),
  'crontabs' =>
  array (
    0 =>
    array (
      'name' => 'MG 未知交易重试',
      'type' => 3,
      'target' => 'app\\service\\game\\GameTask',
      'parameter' => '{"action":"retry","limit":100}',
      'task_style' => 4,
      'rule' => '0 */1 * * * *',
      'singleton' => 1,
      'status' => 1,
      'remark' => '使用原 Bill 号受控重试',
    ),
    1 =>
    array (
      'name' => 'MG 月表预建',
      'type' => 3,
      'target' => 'app\\service\\game\\GameTask',
      'parameter' => '{"action":"tables"}',
      'task_style' => 7,
      'rule' => '0 5 0 1 * *',
      'singleton' => 1,
      'status' => 1,
      'remark' => '每月一号检查当前及未来两个月',
    ),
    2 =>
    array (
      'name' => 'MG 阶梯月费出账',
      'type' => 3,
      'target' => 'app\\service\\game\\GameTask',
      'parameter' => '{"action":"billing"}',
      'task_style' => 4,
      'rule' => '0 10 * * * *',
      'singleton' => 1,
      'status' => 1,
      'remark' => '每小时按商户当地月份幂等生成账单',
    ),
    3 =>
    array (
      'name' => 'MG WXGAME 游戏同步',
      'type' => 3,
      'target' => 'app\\service\\game\\GameTask',
      'parameter' => '{"action":"sync","platform":"wxgame"}',
      'task_style' => 1,
      'rule' => '0 10 3 * * *',
      'singleton' => 1,
      'status' => 1,
      'remark' => '每日同步 WXGAME',
    ),
    4 =>
    array (
      'name' => 'MG AceWin 游戏同步',
      'type' => 3,
      'target' => 'app\\service\\game\\GameTask',
      'parameter' => '{"action":"sync","platform":"acewin"}',
      'task_style' => 1,
      'rule' => '0 20 3 * * *',
      'singleton' => 1,
      'status' => 1,
      'remark' => '每日同步 AceWin',
    ),
    5 =>
    array (
      'name' => 'MG TADA 游戏同步',
      'type' => 3,
      'target' => 'app\\service\\game\\GameTask',
      'parameter' => '{"action":"sync","platform":"tada"}',
      'task_style' => 1,
      'rule' => '0 30 3 * * *',
      'singleton' => 1,
      'status' => 1,
      'remark' => '每日同步 TADA',
    ),
    6 =>
    array (
      'name' => 'MG GoldenGateX 游戏同步',
      'type' => 3,
      'target' => 'app\\service\\game\\GameTask',
      'parameter' => '{"action":"sync","platform":"goldengatex"}',
      'task_style' => 1,
      'rule' => '0 40 3 * * *',
      'singleton' => 1,
      'status' => 1,
      'remark' => '每日同步 GoldenGateX',
    ),
    7 =>
    array (
      'name' => 'MG 统计刷新',
      'type' => 3,
      'target' => 'app\\service\\game\\GameTask',
      'parameter' => '{"action":"stats"}',
      'task_style' => 4,
      'rule' => '0 */5 * * * *',
      'singleton' => 1,
      'status' => 1,
      'remark' => '每 5 分钟校准日报、小时和月度趋势',
    ),
    8 =>
    array (
      'name' => 'MG 汇率同步',
      'type' => 3,
      'target' => 'app\\service\\game\\GameTask',
      'parameter' => '{"action":"exchange_rate"}',
      'task_style' => 4,
      'rule' => '0 10 0 * * *',
      'singleton' => 1,
      'status' => 1,
      'remark' => '每天 00:10 UTC 保存 CurrencyAPI 汇率快照',
    ),
  ),
  'users' =>
  array (
    0 =>
    array (
      'id' => 1,
      'username' => 'admin',
      'realname' => '系统管理员',
      'role' => 'super_admin',
      'password_env' => 'INITIAL_ADMIN_PASSWORD',
    ),
    1 =>
    array (
      'username' => 'game_admin',
      'realname' => '游戏超管',
      'role' => 'game_super_admin',
      'password_env' => 'INITIAL_GAME_ADMIN_PASSWORD',
    ),
  ),
);
